### ISSUE TITLE
webjars not found for oauth2 and oauth2-vanilla

### ISSUE THREAD

**Issue by magiccrafter** [spring-guides/tut-spring-security-and-angular-js#103]
The UI part is not working for both projects:
- oauth2
- oauth2-vanilla

After the upgrade to 1.3.5 it seems that webjars are not being resolved correctly.
I've played a bit with them and I managed to start them both by simplifying the pom.xml files using the webjars-locator dependency.

**Comment by dsyer** [comment]
Works for me. What is it that is "not working"?

**Comment by magiccrafter** [comment]
I've just updated to the latest and the problem that I get in the browser is:
![image](https://cloud.githubusercontent.com/assets/1208518/15570526/be3eb1ba-2336-11e6-8cda-bca6b29f29a9.png)

and the web page at localhost:8080 is blank.

**Comment by dsyer** [comment]
Did you actually run the wro4j build? (You can run it on the command line, or using an IDE plugin.)

**Comment by magiccrafter** [comment]
I missed that step of the process with this approach. I've seen in another example a usage with the webjars-locator and there there was no need running the wro4j build. Thanks a lot.
