### ISSUE TITLE
Logout 

### ISSUE THREAD

**Issue by pasha-gr** [spring-guides/tut-spring-security-and-angular-js#106]
Hi,
I am using Oauth2(JWT) sample app.
I want to completely log user out and as when he puts login button again, be forced to login and enter his username and password again.
I read these issues : 
https://github.com/spring-guides/tut-spring-security-and-angular-js/issues/31
https://github.com/spring-guides/tut-spring-security-and-angular-js/issues/44
https://github.com/spring-guides/tut-spring-security-and-angular-js/issues/37
- I don't want to use spring-session.
- I can't remove cookies from browsers cache because they are http(only)(https://www.owasp.org/index.php/HttpOnly)
- I checked calling 'localhost:8080/logout' and 'localhost:9999/uaa/logout'  together but it was useless.
- I removed tokens from JwtTokenStore. even changed TokenStore to JDBCTokenStore and removed theme for sure but it was useless too. 
- I tried to invoke access_token and refresh_token but it was useless too.

What I must do to logout completely and force user to enter username/password again??
Thanks

**Comment by dsyer** [comment]
The user is authenticated in two places. The client app and the auth server. If you control both you can logout of both of them with a JavaScript client. If you don't then you really shouldn't be trying. What did you try and why didn't it work?

**Comment by pasha-gr** [comment]
Its my code on raw oauth2 sample app : 

```
self.logout = function () {
            $http.post('logout', {}).finally(function () {

                $http.post('localhost:9999/uaa/logout', {})
                    .finally(function () {
                        $rootScope.authenticated = false;
                        $location.path("/");
                    })
                    .error(function (err) {
                        console.log(err);
                    });
                $rootScope.authenticated = false;

                $location.path("/");
            });
```

May I have a sample code?

**Comment by dsyer** [comment]
You've only attempted to log out of one of the apps there, haven't you?

**Comment by pasha-gr** [comment]
Isnt it calls oauthserver logout too ($http.post('localhost:9999/uaa/logout', {})) ? 
I tried this on oauthserver this controller :

```
    @RequestMapping(value = "/logmeout", method = RequestMethod.POST)
    @ResponseBody
    public void logmeout(Principal user, HttpServletRequest request) {
        System.out.println();
        String token = request.getHeader("authorization");
        if (token != null && token.startsWith("bearer ")) {
            OAuth2AccessToken oAuth2AccessToken = tokenStore.readAccessToken(token.split(" ")[1]);
            if (oAuth2AccessToken != null) {
                tokenStore.removeAccessToken(oAuth2AccessToken);
                tokenStore.removeRefreshToken(oAuth2AccessToken.getRefreshToken());
            }
        }
    }
```

honestly I couldn't config  my CustomLogoutSuccessHandler.

**Comment by dsyer** [comment]
Sorry, yes, I was reading it wrong (but why did you reset the `$location` before the success of the uaa logout?). How do you know it isn't working?

**Comment by pasha-gr** [comment]
![2016-06-15_15-39-29](https://cloud.githubusercontent.com/assets/17588118/16077666/833e465a-330f-11e6-8536-41eeb4f91701.png)

;-) 
 Its original code : 

```
    self.logout = function() {
        $http.post('logout', {}).finally(function() {
            $rootScope.authenticated = false;
            $location.path("/");
        });
    }
```

I just copied it! no idea!
I know $http.post('localhost:9999/uaa/logout', {})  redirects me to 'localhost:9999/uaa/login?logout'
I just check the cookies on browser to sure for logout from authserver.
you mean it logs me out from oauthserver and login again?

there is two JSESSION token, one for "/uaa" and one for "/" contextPath. I check them this way.

**Comment by dsyer** [comment]
If you get the redirect to `login?logout` that means it's successful. So what's the problem?

**Comment by pasha-gr** [comment]
Then I see the login button on header, when I click on button I login again without any obstacle(I have set it to autoapproval = true), 
What I must to do to force user enter username/password again??
Thanks
Let me think about your comments and check anything again, I will inform you.

**Comment by dsyer** [comment]
Is the auth server authenticated with HTTP Basic? If it is the browser will remember the credentials for you.

**Comment by pasha-gr** [comment]
Yes it is. I moved to SSL, Now I get this error 
: http://stackoverflow.com/questions/30164516/ssl-proxy-issue-using-spring-cloud-oauth2

**Comment by pasha-gr** [comment]
Hi dear dsyer. 
I resolved the issue with this piece of code :

oauth server side :

```
  @RequestMapping(value = "/logmeout", method = RequestMethod.POST)
    @ResponseBody
    public void logmeout(Principal user, HttpServletRequest request, HttpServletResponse response) {
        System.out.println();
        String token = request.getHeader("authorization");
        if (token != null && token.startsWith("bearer ")) {
            OAuth2AccessToken oAuth2AccessToken = tokenStore.readAccessToken(token.split(" ")[1]);
            if (oAuth2AccessToken != null) {
                tokenStore.removeAccessToken(oAuth2AccessToken);
                tokenStore.removeRefreshToken(oAuth2AccessToken.getRefreshToken());
            }

            Cookie cookie0 = new Cookie("JSESSIONID", null);
            cookie0.setPath("/");
            cookie0.setValue("");
            cookie0.setHttpOnly(true);
            cookie0.setMaxAge(-1);
            response.addCookie(cookie0);
            ///////////////////////
            Cookie cookie2 = new Cookie("XSRF-TOKEN", null);
            cookie2.setPath("/");
            cookie2.setValue("");
            cookie2.setMaxAge(-1);
            response.addCookie(cookie2);
            request.getSession().invalidate();
            SecurityContextHolder.getContext().setAuthentication(null);

       }
    }
```

and in UI side : 

```
 serviceAPI.Logout = function () {
        return $http.post('logmeout', {})
            .success(function () {
                console.log('success logmeout')
                $http.post('/logout', {})
                    .success(function () {
                        console.log('success logout');
                        $rootScope.userAuthenticated = false;
                        $state.go('login')
                    }).error(function (err) {
                    $rootScope.userAuthenticated = false;
                    $state.go('login');
                });
            }).error(function (err) {
                $http.post('/logout', {})
                    .success(function () {
                        console.log('success logout');
                        $state.go('login')
                    }).error(function (err) {
                    $rootScope.userAuthenticated = false;
                    $state.go('login');
                });
                console.log(err)
            });
    };
```

which logmeout has added in zuul :

```
zuul:
  routes:
    user:
       path: /user/**
       url: http://172.17.192.191:9999/authentication/user
    logmeout:
       path: /logmeout/**
       url: http://172.17.192.191:9999/authentication/logmeout
```
