### ISSUE TITLE
View resolver issue in oauth2

### ISSUE THREAD

**Issue by pavanandhukuri** [spring-guides/tut-spring-security-and-angular-js#107]
I have made a clone of the three oauth2 projects and ran them through STS. I am looking at how form login is setup. 

When I click on login, the browser is redirecting to /uaa/login on the authorization server but I am presented the following error.

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 13 11:17:46 IST 2016
There was an unexpected error (type=Internal Server Error, status=500).
Circular view path [login]: would dispatch back to the current handler URL [/uaa/login] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)

```

I looked around and I did not see any configuration for view resolver. Can you tell me if i'm missing something?

Thank you

**Comment by dsyer** [comment]
You didn't say exactly which code you are running. All the sample apps work for me last time I checked.

**Comment by pavanandhukuri** [comment]
I am running the three apps (authorize, resource and ui) from oauth2 folder. Where form based login is implemented over the vanilla oauth2 version.

**Comment by dsyer** [comment]
Works for me running from master.

**Comment by pavanandhukuri** [comment]
Are there steps to be followed or some configuration to be done to map the "/login" to the login.ftl file? 

How is the login.ftl file served when the page redirects to /uaa/login. I am running the apps from STS only as spring boot apps. 

Am I missing something? 

Thank you.

**Comment by dsyer** [comment]
Maybe you need to add some plugins to STS? I just ran it all from the command line with `mvn spring-boot:run` and it worked. Why don't you try that.

**Comment by pavanandhukuri** [comment]
The freemarker jar file in my maven repository was corrupt. I have re downloaded it and it started working. 

Sorry for the trouble and thank you.
