### ISSUE TITLE
How to use a different tokenstore ?

### ISSUE THREAD

**Issue by hlassiege** [spring-guides/tut-spring-security-and-angular-js#11]
Hi,

I'm playing with the oauth2 sample. 

I've tried to change the token store to use a MongoDBTokenStore.
I tried with an implementation of a token store found in jhipster. But I always get an error just after the confirmationForm (in authorize.ftl)

There was an unexpected error (type=Unauthorized, status=401).
Authentication Failed: Could not obtain access token

I modified the AuthserverApplication to add the creation of the bean : 

```
    @Inject
    private OAuth2AccessTokenRepository oAuth2AccessTokenRepository;

    @Inject
    private OAuth2RefreshTokenRepository oAuth2RefreshTokenRepository;

    @Bean
    public TokenStore tokenStore() {
        return new MongoDBTokenStore(oAuth2AccessTokenRepository, oAuth2RefreshTokenRepository);
    }
```

Then I use it in OAuth2AuthorizationConfig 

I've written some comments in the code to explain the modication. 

```
        // injection of the mongodb token store 
        @Autowired
        private TokenStore tokenStore;


         // I commented this part because I don't think I need it if I use a persistent token store. But I'm not sure to understand correctly what it does.
//        @Bean
//        public JwtAccessTokenConverter jwtAccessTokenConverter() {
//            JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
//            KeyPair keyPair = new KeyStoreKeyFactory(
//                    new ClassPathResource("keystore.jks"), "foobar".toCharArray())
//                    .getKeyPair("test");
//            converter.setKeyPair(keyPair);
//            return converter;
//        }

        @Override
        public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
            clients.inMemory()
                    .withClient("acme")
                    .secret("acmesecret")
                    .authorizedGrantTypes("authorization_code", "refresh_token", "password")
                    .scopes("openid");
        }

        @Override
        public void configure(AuthorizationServerEndpointsConfigurer endpoints)
                throws Exception {
            endpoints
                    .tokenStore(tokenStore)
                    .authenticationManager(authenticationManager)
            ;
        }

        // I didn't understand this part and I've tried with or without with no success.
//        @Override
//        public void configure(AuthorizationServerSecurityConfigurer oauthServer)
//                throws Exception {
//            oauthServer.tokenKeyAccess("permitAll()").checkTokenAccess(
//                    "isAuthenticated()");
//        }
```

I've tried a lot of things : 
- disable the crsf settings (but without any success, I had some errors saying that a token is expected)
- inject the tokenstore in OAuth2ResourceConfig to initialize the ResourceServerSecurityConfigurer with it
- etc...

But to be honest, a lot of configurations seems obscure for me. 

Any idea ?

**Comment by dsyer** [comment]
Looks pretty sane to me. It would probably help to look at the logs from the auth server (with `logging.level.org.springframework.security=DEBUG`).

Clearly you will need the token store in your resource server as well, but that's a different problem. CSRF has no bearing on the token endpoint because it is a back channel.

**Comment by hlassiege** [comment]
I finally found the problem. It was because I didn't register correctly a mapping converter in the mongotemplate. 
The error was not very clear but it's ok now.
