### ISSUE TITLE
Separate the section on Front End Assets

### ISSUE THREAD

**Issue by oleersoy** [spring-guides/tut-spring-security-and-angular-js#111]
First wanted to say thanks again for writing these brilliant tutorials.  I think first section would be more focused if the front end asset section was separated into its own tutorial and linked to.  I find myself scrolling over that section each time I review the material.

**Comment by dsyer** [comment]
Thanks for the suggestion. Can you be a bit more specific? Which bits do you scroll through?

**Comment by oleersoy** [comment]
Sure - The section on producing the assets:
https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/basic/README.adoc#front-end-assets

This section, while really great - was not aware of the tooling - is a bit of a departure from the core article concept of performing a secure login with angular, so if it's separated out and linked to I think the article will flow better.

**Comment by dsyer** [comment]
Not really relevant any more (all assets are fetched from webjars).

**Comment by oleersoy** [comment]
Yeah the whole thing is moving it looks like there are several new articles upgraded to Angular4 already.  This was one of my favorites though.  I keep coming back to it to learn.  I love how it starts with basics and builds on it so we can get the big picture.  Just got done reviewing your article on OAuth2 CSRF attacks, which was really awesome as well.  Thanks again for sharing all this stuff.  Its Genius!
