### ISSUE TITLE
Logout redirects to /login?logout

### ISSUE THREAD

**Issue by Busata** [spring-guides/tut-spring-security-and-angular-js#113]
I was following this guide, but my front-end project is separated from the spring boot project. After the first part, completing the angular login form & logout, logging out makes spring redirect you to a /login?logout page. Since he'll search for this path on the server, you get a 404 on the front end.

I found the solution for this to define a custom logoutsuccesshandler with HttpStatusReturningLogoutSuccessHandler as handler. Perhaps this is handy to mention in the tutorial itself to spare (poor! poor!) users like myself to scroll up & down to double check everything..

**Comment by dsyer** [comment]
It doesn't actually affect the user experience in the guide samples though, so I'm not sure it's worth calling out explicitly. I'll have a think about it (it's easy to change anyway).

**Comment by uralovs** [comment]
If its easy to change anyway, how would we do it?

**Comment by dsyer** [comment]
The OP said what he did to change it. Actually with the latest codebase (new Spring Security version since the guide was first written) the /logout sends a 204 (not a 302), so you shouldn't have to change anything.
