### ISSUE TITLE
Question - In the OAuth2 + JWT version. How jwt token is sent to 'resource' server

### ISSUE THREAD

**Issue by ksambhav** [spring-guides/tut-spring-security-and-angular-js#114]
The 'oauth2-ui' has zuul proxy configured that forwards request to /resource to the :9000  resource service.

Q1. How the JWT token issued by oauth2-authserver reaches the resource server. Is the 'JSESSIONID' is the jwt token ? If yes, where this magic happens that sets jwt token in JSESSIONID?

What if i what the browser to use 'resource' server directly  without going through the zuul proxy once I have taken care of CORS.

**Comment by ghost** [comment]
I have the same question as @ksambhav What the point to use JWT if token itself does not stored in a browser cookie. Could someone please provide example how to implement stateless SSO auth by using JWT?

**Comment by dsyer** [comment]
@ksambhav: The session id is the normal one as generated by the server (not a JWT). The magic is the relay of the session id in the proxy to the access token in the backend (via a Zuul filter that is part of Spring Cloud Security). You could do it yourself manually by pulling the `OAUth2Authentication` out of the `SecurityContext` and extracting the access token from there.

@mxbyrd: Using access tokens as cookies is not really best practice AFIK (they have different lifetimes). I think the resource servers in this sample are "stateless" in the sense you mean (they only need the information in the token to make an access decision).
