### ISSUE TITLE
Why did you remove 'var' enter = ...?

### ISSUE THREAD

**Issue by LouisWayne** [spring-guides/tut-spring-security-and-angular-js#115]
In the commit f2ccc36, I found weird change in the file: _modular/src/main/resources/static/js/auth/auth.js_

The original code is:

```
...
var enter = function() {
...
```

But now we don't have the word: 'var'.

```
...
enter = function() {
...
```

Is it mistake? or is there a reason for that?

**Comment by dsyer** [comment]
It was a mistake. The difference is well explained here in case anyone cares: http://stackoverflow.com/questions/1470488/what-is-the-purpose-of-the-var-keyword-and-when-to-use-it-or-omit-it.
