### ISSUE TITLE
Authority being parsed incorrectly

### ISSUE THREAD

**Issue by ChrisCooney** [spring-guides/tut-spring-security-and-angular-js#119]
I've set up a userInfoUri URI in the config file. Authentication is working well, however Authorization isn't. I can see from the debugger that the Authority that it attempting to find is incorrectly parsed.

I've attached a link to a screenshot indicating the incorrectly parsed authority. Is this something that you guys have seen before? 

http://prntscr.com/c9h8el

**Comment by dsyer** [comment]
Sorry, but there isn't sufficient information yet to offer any suggestions. If you maybe modified one of the samples here you could link to your fork and we could look at the code.

**Comment by dsyer** [comment]
Closed for lack of feedback.

**Comment by ChrisCooney** [comment]
Completely forgot about this. Apologies.

The work around for this was to use the token information endpoint instead of the user information endpoint.
