### ISSUE TITLE
csrf problem - double sample (api gateway pattern two ui apps)

### ISSUE THREAD

**Issue by ccasallas** [spring-guides/tut-spring-security-and-angular-js#120]
I download and run this sample (https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/double) and it works almost perfect. However, Admin ui has a problem updating greeting (Post method to /resource):

```
{
   "timestamp":1472071314262,
   "status":403,
   "error":"Forbidden",
   "message":"Could not verify the provided CSRF token because your session was not found.",
   "path":"/"
}
```

Does someone know how resolve this problem?

**Comment by dsyer** [comment]
You can work round it by adding `.csrf().disable()` in the `ResourceApplication`. I'll work on it a bit to get a better solution (the problem, I think is that I cut some corners with the redis session storage).
