### ISSUE TITLE
oauth2 example, authserver doesnt work in HTTPS when enabled

### ISSUE THREAD

**Issue by nam-pt-do** [spring-guides/tut-spring-security-and-angular-js#122]
Hi,

On the oauth2 example, with the authserver I turned on HTTPS in the application.properties.

```
FILE:  ./oauth2/authserver/src/main/resources/application.properties

server.port: 9999
server.contextPath: /uaa
server.ssl.enabled=true                                            #added the ssl configs
server.ssl.key-store=classpath:keystore.jks              #reused the certs in auth
server.ssl.key-store-password=foobar                     #reused password
security.user.password: password
logging.level.org.springframework.security: DEBUG
```

Then on the UI, i reference my authserver HTTPS url instead of HTTP.

```
FILE: ./oauth2/ui/src/main/resource/application.yml

  oauth2:
    client:
      accessTokenUri: https://localhost:9999/uaa/oauth/token                     # changed to HTTPS
      userAuthorizationUri: https://localhost:9999/uaa/oauth/authorize      # to match above authserver
      clientId: acme
...
    user:
      path: /user/**
      url: https://localhost:9999/uaa/user    # changed to HTTPS to match authserver

```

I see the redirect to HTTPS and i login correctly in HTTPS
![image](https://cloud.githubusercontent.com/assets/18315160/18863839/5226b6e4-8448-11e6-8938-34e66d65706b.png)

I get the Authorize dialog in HTTPS
![image](https://cloud.githubusercontent.com/assets/18315160/18863863/7a4729e2-8448-11e6-8805-c32445928a42.png)

Then when the redirect back to the UI login, i get this.

![image](https://cloud.githubusercontent.com/assets/18315160/18863624/2e475388-8447-11e6-9ffb-296008f25727.png)

The logs from UI says failed because of badcredentials.

The same credentials with authserver in HTTP it works.. but in HTTPS it doesnt work.

Any info is greatly appreciated.

Thanks,

Nam

```
lientAuthenticationProcessingFilter'
2016-09-27 00:25:07.041 DEBUG 11912 --- [nio-8080-exec-8] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/login'; against '/login'
2016-09-27 00:25:07.041 DEBUG 11912 --- [nio-8080-exec-8] uth2ClientAuthenticationProcessingFilter : Request is to process authentication
2016-09-27 00:25:07.043 DEBUG 11912 --- [nio-8080-exec-8] o.s.b.a.audit.listener.AuditListener     : AuditEvent [timestamp=Tue Sep 27 00:25:07 PDT 2016, principal=UNKNOWN, type=AUTHENTICATION_FAILURE, data={type=org.springframework.security.authentication.BadCredentialsException, message=Could not obtain access token}]
2016-09-27 00:25:07.044 DEBUG 11912 --- [nio-8080-exec-8] uth2ClientAuthenticationProcessingFilter : Authentication request failed: org.springframework.security.authentication.BadCredentialsException: Could not obtain access token

org.springframework.security.authentication.BadCredentialsException: Could not obtain access token
        at org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication(OAuth2ClientAuthenticationProcessingFilter.java:107) ~[spring-security-oauth2-2.0.10.RELEASE.jar!/:na]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-4.1.1.RELEASE.jar!/:4.1.1.RELEASE]
   ...
```

**Comment by nam-pt-do** [comment]
Here are some further detail of HTTP authserver works but HTTPS authserver fails.
I look the call flows between the 2 cases, they are different at the 302 redirect from UI to target authserver.

**GOOD CASE:  ui redirect to  HTTP authserver**
  There is NO extra set cookie from ui server redirect to HTTP auth server URL
![image](https://cloud.githubusercontent.com/assets/18315160/18886338/5b8a6e40-84a4-11e6-9d7a-1b5ce56c7cc5.png)

**BAD CASE: ui redirects to HTTPS authserver**
  There is an EXTRA cookie from ui server redirect to HTTPS auth server URL
![image](https://cloud.githubusercontent.com/assets/18315160/18886441/be71a9ec-84a4-11e6-99ad-7ba1d30f2723.png)

Why does the cookie exchange pattern differ from HTTP and HTTPS for the target authserver?
Shouldn't they be the same?

**Comment by nam-pt-do** [comment]
Here's some more details.

The code where the exception is happening is here in Git Hub:

https://github.com/spring-projects/spring-security-oauth/blob/65d5f332e93ebaa2b11702a72597603daa4614d3/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/filter/OAuth2ClientAuthenticationProcessingFilter.java#L107

There's an "OAuth2Exception", in getting the access token, but it's not clear what the root failure is.

![image](https://cloud.githubusercontent.com/assets/18315160/18896591/d4369494-84d7-11e6-9695-2621a04daef5.png)

**Comment by dsyer** [comment]
The problem is the unsigned certificate. Your web client is barfing on the SSL connection back to the auth server (first when it tries to get the token, and then later, potentially, when it tries to get the /user details).

**Comment by nam-pt-do** [comment]
Make sense.  I was confused by the error in the log:

This came from the spring-security module from the ui gateway app when logging in to self signed HTTPS authserver.

```
org.springframework.security.authentication.BadCredentialsException: 
  Could not obtain access token
```

That implied that the client secret configs were wrong on the UI side.  
But the root cause is on the authserver.

When you activate self-signed SSL on the resource app.
you get from Zuul routing when it tries to access the self signed HTTPS sever.

```
javax.net.ssl.SSLPeerUnverifiedException: 
  Host name 'localhost' does not match the certificate subject ...
```

The Zuul's message more than accurate the Spring security one.  

A small suggestion to help others.

Perhaps spring security oauth2 code should try to preserve the original HTTPClient request exception?

Thanks

**Comment by dsyer** [comment]
Thanks for the suggestion. This isn't the right forum to discuss it, but I think it's unlikely to be changed in Spring Security because in general you have to avoid logging details of authentication exceptions to prevent leakage of credentials or other sensitive information.

**Comment by demetrio345** [comment]
Hi, I did the same and I add a self-signed certificate with the Common Name: localhost
But now I'm getting this exception when login through UI App. 

`org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://localhost:9999/BCM/uaa/oauth/token": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

My certificate has the localhost Certification Path and his status is OK.
As I was reading in some posts, I already add it to my local java keystore(cacerts file), but still getting the error.
Do you have any idea of how can I solve it?
PD: If I access via postman to auth and resorce servers everything works fine.
Thank you

**Comment by Nisreen123** [comment]
@demetrio345
did you find a solution for this, i added a new filter before the BasicAuthenticationFilter
`.addFilterBefore(handleSSLFilter(), BasicAuthenticationFilter.class)`

where handleSSLFilter as follows:
`private Filter handleSSLFilter() throws Exception {
        OAuth2ClientAuthenticationProcessingFilter oauthFilter = new OAuth2ClientAuthenticationProcessingFilter("/login");
        OAuth2RestTemplate oauthTemplate = new OAuth2RestTemplate(resource, oauth2ClientContext);
        OAuth2AccessTokenSupport authAccessProvider = new AuthorizationCodeAccessTokenProvider();
        // Set request factory for '/oauth/token'
    	// self signed certificate    	
		SSLContext sslContext = SSLContexts.custom().loadTrustMaterial(null, new TrustSelfSignedStrategy()).build();
		SSLConnectionSocketFactory sslsf = new SSLConnectionSocketFactory(
						sslContext, new HostnameVerifier() {
						@Override
						public boolean verify(String hostname,
								SSLSession session) {
							return true;
						}});
		
		CloseableHttpClient httpClient = HttpClients.custom()
                .setSSLSocketFactory(sslsf)
                .build();
		
		ClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory(httpClient);
        authAccessProvider.setRequestFactory(requestFactory);
        AccessTokenProvider accessTokenProvider = new AccessTokenProviderChain(Arrays.<AccessTokenProvider> asList(
                (AuthorizationCodeAccessTokenProvider)authAccessProvider));
        oauthTemplate.setAccessTokenProvider(accessTokenProvider);
        
        oauthFilter.setTokenServices(tokenServices());
        oauthTemplate.setRequestFactory(requestFactory);
        oauthFilter.setRestTemplate(oauthTemplate);
        return oauthFilter;
    }`
but the logic of the refreshToken is broken due to the same exception, i cannot imagine that there is no simpler approach especially that the Authorization server must to be accessed over ssl

**Comment by shanmugavadivelu1990** [comment]
I am having the same issue; I am using Self signed certificate created in java and changed HTTP to HTTPS for my web page.

I am also using OAuth2 in my project.

This is what I am getting when I click on login (request authorize to Oauth2)

**Log in my micro service:**

2018-07-31 14:51:40.338 ERROR 9224 --- [nio-8484-exec-3] c.s.v.controllers.CustomErrorController  : [https://localhost:8484/login] [401] Authentication Failed: Could not obtain access token

**Log in Oauth2 micro service:**

2018-07-31 14:51:03.847  INFO 3904 --- [nio-9999-exec-8] o.s.b.a.audit.listener.AuditListener     : AuditEvent [timestamp=Tue Jul 31 14:51:03 IST 2018, principal=admin, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@fffde5d4: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: 0F52F136806BEF9FA3810E963763D444}]

Here is what is output from browser:

![image](https://user-images.githubusercontent.com/41955394/43458707-d90b9f82-94e8-11e8-8008-117044d16f84.png)

**Comment by eskuai** [comment]
Same problem

![imagen](https://user-images.githubusercontent.com/1777753/62937162-16805d00-bdcc-11e9-8307-1e59c88568f5.png)
