### ISSUE TITLE
Special Thanks 

### ISSUE THREAD

**Issue by damozhiying** [spring-guides/tut-spring-security-and-angular-js#123]
i have a requirement in my project , i must according to the user info and then ui gateway route to diff ip,how i show do ,
flow diagram is  when brower is open , the ui gateway route to the sso system,then redirectory to the ui gateway,the ui gateway according to the session get the user info, then if
                       the user id  is 123456,now the ui gateway  Forward to 192.168.1,11
                      the user id is 234567 ,now the ui gateway forward to 192.168.1.23
the 192.168.1,11 and 192.168.1.23 system is same,
the main problem is according  to session to route to diff system,

**Comment by dsyer** [comment]
Please limit issues in this project to actual feature requests and bugs for the sample apps.
