### ISSUE TITLE
Missing "ignored" comments

### ISSUE THREAD

**Issue by oleersoy** [spring-guides/tut-spring-security-and-angular-js#126]
Hi - In this section some responses (Probably the 401s) are supposed to be marked as ignored:
https://github.com/oleersoy/tut-spring-security-and-angular-js/blob/master/single/README.adoc#how-does-it-work

> The responses that are marked "ignored" above ...

But they are not marked ... I've seen other tables where they are marked in the other tutorials

**Comment by dsyer** [comment]
Thanks. Fixed in e4ee6ea.
