### ISSUE TITLE
How can I create a public REST API using the Auth-Resource-UI approach?

### ISSUE THREAD

**Issue by cvenegasj** [spring-guides/tut-spring-security-and-angular-js#129]
I want to create a public REST API but apparently, the Resource Server is only allowed to respond to authenticated requests. Where should I put the public rest controllers? Is there a way for using the same Resource Server an avoid creating the entity and dao clases again in other server?

Thanks in advance for the reply.

**Comment by dsyer** [comment]
Take a look at the [Spring Security User Guide](http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/) and other resources (e.g. type "security" in the search box at https://spring.io/guides). It's just a matter of changing the access rules for the paths you want to protect/unprotect.
