### ISSUE TITLE
Add "Message" POJO definition to Resource application

### ISSUE THREAD

**Issue by gregturn** [spring-guides/tut-spring-security-and-angular-js#130]
When creating the Resource application for the first time, this can be seen:

```
@RequestMapping("/")
@CrossOrigin(origins = "*", maxAge = 3600)
public Message home() {
	return new Message("Hello World");
}
```

However, the `Message` type isn't defined. Would be handy to include this in the code as well.

**Comment by dsyer** [comment]
Fixed in 922de14
