### ISSUE TITLE
Documentation issue under  Single Sign On with OAuth2/Changing the Resource Server

### ISSUE THREAD

**Issue by gergogera** [spring-guides/tut-spring-security-and-angular-js#135]
The documentation under  Single Sign On with OAuth2/Changing the Resource Server (oauth2-vanilla) suggests to replace the spring-session and spring-boot-starter-redis maven dependencies to spring-security-oauth2. According to your pom.xml we need to add the spring-cloud-starter-oauth2 as well and it was not working for me without it.

**Comment by dsyer** [comment]
I think you referred to the wrong section (the resource server doesn't need the cloud starter but the UI app does). Thanks anyway.
