### ISSUE TITLE
How will static resources from UI be loaded via Gateway

### ISSUE THREAD

**Issue by hi2karthik** [spring-guides/tut-spring-security-and-angular-js#143]
On following 
https://spring.io/guides/tutorials/spring-security-and-angular-js/#_multiple_ui_applications_and_a_gateway_single_page_application_with_spring_and_angular_js_part_vi

I couldn't find any discussion on how static resources like CSS and JS will be loaded from UI server via the Gateway.

Getting a bunch of 404 errors

**Comment by hi2karthik** [comment]
looks like it is handled implicitly

There seems to be a difference between
http://localhost:8080/ui/
and 
http://localhost:8080/ui

Can you please elaborate?

**Comment by dsyer** [comment]
Tomcat sends a 302 to a request without a trailing slash. AFAIK there's no way to change it.
