### ISSUE TITLE
Integration with Node.js application

### ISSUE THREAD

**Issue by ghsbhatia** [spring-guides/tut-spring-security-and-angular-js#144]
@dsyer I followed the tutorial to create a spring-session application and use the x-auth-token to securely access another REST service in java which is backed by the same redis instance. It works like charm. I am now exploring a mechanism so that a microservice written in Node.js can use the same x-auth-token. One of the option would be to store the session information using json rather than serialized java object. I would like to seek your feedback as well as any other options that you may suggest.

**Comment by dsyer** [comment]
The spring-session token is my least favourite sample app in this tutorial - it's kind of a stepping stone, and a way to show you what's possible without really recommending it. Having said that I don't see any reason it wouldn't work with a JavaScript client. Not sure why you would want to convert the token to JSON (it's supposed to be opaque).

**Comment by ghsbhatia** [comment]
Thanks for your reply. I am thinking thru why you wouldn't recommend for the scenario above and one good reason would be that the API aouldn't be OAUTH compliant. So if this service was to be exposed to public, clients would have to provide custom connectors to manage x-auth-token thus preventing them from using standard libraries that are bearer token based. Is that so?

**Comment by dsyer** [comment]
Yeah, using a standard would probably make more sense in a real system, and especially one with a public API. Also, there is the possibility that the shared session leaks of overwrites data from other apps if you aren't careful.
