### ISSUE TITLE
[tut-spring-security-and-angular-js/oauth2] Circular view path [login]

### ISSUE THREAD

**Issue by franck-serot** [spring-guides/tut-spring-security-and-angular-js#146]
I cloned the project tut-spring-security-and-angular-js/oauth2.
I executed springboot:run on the modules authserver, resource and ui.
I started the ui application.
When I selected login link then I have the following error :

```
javax.servlet.ServletException: Circular view path [login]: would dispatch back to the current handler URL [/uaa/login] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
```

The problem seems provide of access to the templates for freemarker.
I tried to update of freemarker in the application.properties file but with no success.

Could you help me to resolve this problem ?

**Comment by dsyer** [comment]
Works for me. Since you mention freemarker I guess it's the "oauth2" sample (not the "oauth2-vanilla"). Both work for me though.

I think you mean "mvn spring-boot:run"? Did you "mvn install" them first?

**Comment by franck-serot** [comment]
I worked on the project "oauth2" (cf title [tut-spring-security-and-angular-js/oauth2])
I started the ui application with "mvn spring-boot:run".
I tried "mvn clean install" but I the same problem /

```
javax.servlet.ServletException: Circular view path [login]: would dispatch back to the current handler URL [/uaa/login] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
```

This is the log file : [log.txt](https://github.com/spring-guides/tut-spring-security-and-angular-js/files/955584/log.txt)

**Comment by dsyer** [comment]
Can you list each command you run (including "cd" etc)? It still works fine for me.

**Comment by franck-serot** [comment]
The problem occurs because freemarker is invalid.

[WARNING] error reading D:\.m2\repository\org\freemarker\freemarker\2.3.25-incubating\freemarker-2.3.25-incubating.jar; invalid LOC header (bad signature)

I removed freemarker from my local maven repository.
If I re-executed 'mvn clean install' then the test passed without the error.
I can start ui application and check the autehntification feature.

It's not a bug but just a invalid java library.
