### ISSUE TITLE
CSRF-TOKEN not sending in response which creates a new session

### ISSUE THREAD

**Issue by xak2000** [spring-guides/tut-spring-security-and-angular-js#15]
**This is for `single` subproject.**

For example if we just do `GET /user` with valid `Authorization` header then in response there are no `XSRF-TOKEN` cookie as `CsrfHeaderFilter` thinks that token from `request` is not changed. But actially token is changing on creating a new session.

As a result if we try to instantly do any `POST` (for example `POST /logout`) then it doesn't work until we `GET` any resource.

I found a solution.
Instead of doing
`.addFilterAfter(new CsrfHeaderFilter(), CsrfFilter.class)`
I doing
`.addFilterAfter(new CsrfHeaderFilter(), SessionManagementFilter.class)`

I think that `SessionManagementFilter` creating a new CSRF token when creating a new session for authenticated user. So now when we do `request.getAttribute(CsrfToken.class.getName())` then we get a new token and all working fine.

**Comment by caprica** [comment]
I'm very interested in the "right" way to solve this.

The problem can be demonstrated in this project very easily by removing the GET '/resource' request in the 'home' controller in the Javascript. After login, if you immediately try and logout you will see a 403 Forbidden response with this message: "Expected CSRF token not found. Has your session expired?".

As xak2000 says, after a successful login if there is no intermediate GET request before a POST the POST will fail. Doing any sort of GET masks the problem so in a sense this example app is 'cheating' a bit. :-)

Is it really as simple as changing the filter class as suggested? Are there any downsides to doing so?

**Comment by dsyer** [comment]
I think that's the correct solution because it delays the CSRF cookie from being sent until the session has changed. It was bugging me too, but I didn't have time to get to the bottom of it because the app worked.

CC @rwinch because we had a change lined up for Spring Security 4.0 that might be relevant (or might obsolete all of the code here, hopefully).

**Comment by rwinch** [comment]
We ran out of time to include something in 4.0. The issue to track is [SEC-2891](https://jira.spring.io/browse/SEC-2891).

The suggested approach will work, but I think that a correct approach is going to require more thought (this is why we needed to push the change till 4.1)

**Comment by davinkevin** [comment]
Having the same problem, should be include at least in the documentation until the modification is done in the framework... 

Thanks

**Comment by dsyer** [comment]
Thank you for your interest. If you are looking for a new feature in Spring Security then please follow the link above to the issue that Rob raised. If you want to fix your app just go ahead an follow the recipe outlined by @xak2000. There's no "framework" in this repository.

**Comment by davinkevin** [comment]
I've followed the ticket and integrate the modification inside my AngularJS App dedicated to training / formation https://github.com/davinkevin/betmanager

@dsyer I think the AngularJs code wroted is pretty basic, rought... if you want I can do a PR to have better AngularJS code, for example based on promised instead of .success / .error...

**Comment by dsyer** [comment]
Sure. That would be very interesting.

**Comment by valshin** [comment]
xak2000, thank you! You saved a lot of my time!

**Comment by SviatoslavFedechko** [comment]
xak2000 thank you, I was making crazy about this issue.

**Comment by snake404** [comment]
Hi, sorry for reply a closed thread but in this case, how do you manage the maximum number of sessions? In my spring security configuration, I have this:

`http.httpBasic().and()
        .logout().logoutSuccessUrl("/")
        .invalidateHttpSession(true)
        .and().anonymous().and()
        .authorizeRequests().antMatchers(PUBLIC_URLS).permitAll()       .regexMatchers("views/(clientContent|registrycontent|userDataContent|thirdAccounts|accountsList|operatorFirstLogin|)\\.html").hasRole("OPERATOR")
        .anyRequest().authenticated()
        .and()
        .csrf().csrfTokenRepository(csrfTokenRepository())      
        .and()
        .addFilterAfter(csrfHeaderFilter(), SessionManagementFilter.class) //CsrfFilter.class before saw this post
        .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.NEVER)
        .maximumSessions(1)
        .maxSessionsPreventsLogin(true)
        .sessionRegistry(sessionRegistry()); //this is to store all the sessions`

So the sessionManagement wont work for me, I have to Iterate in all the sessions and check if the user has an active session:

`public class DomainAuthenticationProvider implements AuthenticationProvider{   

```
private static final String AUTHENTICATION_ERROR = "Usuario o password inválidos";
private static final String ACTIVE_SESSION_ERROR = "Usted ya tiene una sesión activa";

@Autowired
private AuthenticateService authService;

@Autowired
private UserLogService logService;

@Autowired
private SessionRegistry sessionRegistry;    

@Override
public Authentication authenticate(Authentication authentication)
        throws AuthenticationException{
    final String username = authentication.getName();
    final String password = (String)authentication.getCredentials();        
    List<Object> list = sessionRegistry.getAllPrincipals();     

            //Check if the user has an active session
    for(Object s : list){
        BackOfficeUserDetails user = (BackOfficeUserDetails) s;         
        if(user.getEmail().equals(username)){
            //sessionRegistry.getSessionInformation(sessionId)
            List<SessionInformation> userSessions = sessionRegistry.getAllSessions(user, false);
            if(!userSessions.isEmpty()){
                throw new RuntimeException(ACTIVE_SESSION_ERROR, new AccessDeniedException(ACTIVE_SESSION_ERROR));
            }                
        }                           
    }

    //Validate User
    if(authService.validateUser(authentication)){
        //Log login event
        logService.insertLoginEvent(username, new GregorianCalendar().getTime());

        //Get details
        BackOfficeUserDetails user = authService.getUserInfo(username);         
        return new UsernamePasswordAuthenticationToken(user, password, user.getAuthorities());          
    }else{
        throw new RuntimeException(AUTHENTICATION_ERROR, new BadCredentialsException(AUTHENTICATION_ERROR));            
    }
}

@Override
public boolean supports(Class<?> klass){        
    return true;
}   
```

}`

But I have a problem when the user send an invalid session token in the logout flow. spring security creates a new session when I try to login after I send an invalid session token, so when I check if the user has an active session, the exception above occurs, and this is every time that I try to login.
So can anyone help me with this part?
Sorry for ask this in this issue, I've posted my question in stackoverflow but I didn't receive an answer and I didn't found any solution yet.

**Comment by dsyer** [comment]
This is a closed thread about csrf tokens. It's not really a good idea to tack on new questions about unrelated topics. If you have an issue with the code in this tutorial please open another ticket.
