### ISSUE TITLE
Documentation Error for Proxy Section

### ISSUE THREAD

**Issue by ghost** [spring-guides/tut-spring-security-and-angular-js#152]
The Dependency under "Sharing Authentication State" in "README.adoc" is wrong:

_<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-redis</artifactId>
</dependency>_

**It has to be:**
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>**spring-boot-starter-data-redis**</artifactId>
</dependency>

**Comment by gregturn** [comment]
Pull request welcome!
