### ISSUE TITLE
Polymer SPA

### ISSUE THREAD

**Issue by HJK181** [spring-guides/tut-spring-security-and-angular-js#153]
First of all thank you for your article and very nice examples, they are really great and a good starting point even for beginners.

Could you give us an example or hint on how to use Polymer for the SPA? I found this [repo](https://github.com/sdeeg-pivotal/spring-polymer-demo) which gives a basic idea of how it could work. What I'm missing though is how to run a build Polymer app. With build I mean using the Polymer CLI to minify CSS, JS etc. by issuing the `polymer build` command.

**Comment by dsyer** [comment]
This is kind of out of scope, and I'm not a polymer user, but I expect you can play one of the tricks that react or angular users play to use their npm build tools. My favourite is to symlink the build result from npm into src/main/resources/static in my Boot app. Maybe if you ask Scott a question in that other repo you linked to that would be better?

**Comment by HJK181** [comment]
Thank you very much Dave. I created an Issue on the other repo as well and will try your suggestion.

**Comment by dsyer** [comment]
See also example here for Angular (where npm build results are deposited directly in the spring boot target): https://github.com/dsyer/spring-boot-angular.
