### ISSUE TITLE
Why is the content of your article inconsistent with the source code?

### ISSUE THREAD

**Issue by immno** [spring-guides/tut-spring-security-and-angular-js#154]
https://spring.io/blog/2015/02/03/sso-with-oauth2-angular-js-and-spring-security-part-v
https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/oauth2

**Comment by dsyer** [comment]
You'll have to be more specific than that. Also the tutorial is more up to date than the blog (there's a link in the blog right at the top there). The source code for the tutorial text is also there in GitHub, so links with line numbers would help to narrow down the problem.

**Comment by dsyer** [comment]
No response. Please be more specific and/or send a pull request next time.
