### ISSUE TITLE
 CSRF token value stored in Redis -Spring-Session Project in master branch

### ISSUE THREAD

**Issue by mingqin1** [spring-guides/tut-spring-security-and-angular-js#156]
Hi Dave Syer:
    In the blog ( https://spring.io/blog/2015/01/20/the-resource-server-angular-js-and-spring-security-part-iii), there is a statement that is “and the session data (the authentication and CSRF token) will be stored in redis”.   After running the spring-session subproject in master branch,  the radis-cli command ( keys “*” ) displayed following keys

**_127.0.0.1:6379> keys "*"_**
**_1) "spring:session:sessions:expires:6fa7ae8e-4e31-4447-9466-1fd37d42a751"_**
**_2) "spring:session:expirations:1503238860000"_**
**_3)"spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:user"_**
**_4) "spring:session:sessions:6fa7ae8e-4e31-4447-9466-1fd37d42a751"_**

    It seems CSRF token value was still stored in httpSession , but not in redis.  If my observation is correct, could CSRF  token value be stored in Redis by Spring-Session ?

**Comment by dsyer** [comment]
I'm not really sure what you're getting at. The session is in Redis, until it expires or is ended. It happens to contain both authentication and csrf data in the sample you are taking about. That's it really, and that's what the text says. What's the problem, or the question?

**Comment by mingqin1** [comment]
Hi Dave:
    In Spring-Session example, after logging in, I try to find out chrome cookie XSRF-TOKEN value in redis. Because I believed that cookie XSRF-TOKEN value is stored in Redis as SESSION cookie value does.
   Here are steps:
 Following pictures were obtained from chrome dev tool after users login as user and password. The XSRF-TOKEN value is 1fd1ec84-c3bf-4e21-afa8-ffb92986fcb2
![capture1](https://user-images.githubusercontent.com/6629272/29498182-abb3d056-85ab-11e7-8079-7e4d6d3c8057.PNG)

 In Redis Console, I could not find CSRF token value as 1fd1ec84-c3bf-4e21-afa8-ffb92986fcb2
![capture2](https://user-images.githubusercontent.com/6629272/29498198-e0d544c2-85ab-11e7-9521-1c6623e319ba.PNG)

Thanks 
Ming Qin

**Comment by dsyer** [comment]
I don't know how that redis console works. You'd have to look inside the session to find the stored csrf token. Why would you need to do that though?

**Comment by mingqin1** [comment]
Dave: 
   I wish I could detect  inauthentic csrf  toke  by deleting or altering csrf token in redis, then reloading http://localhost:8080/#/ in chrome browser, as well as understanding horizontal scalabilities in using external cache to store CSRF
   
   Right now, I suspected the example ( Spring-Session) had csrf token being stored at the outside of redis.  
   What I did was after starting up redis and spring-Session servers,  browser loaded up http://localhost:8080/, the browser got XSRF-TOKEN( **dc80a12d-2a51-47a4-9858-4c08801c7257**)  But redis-cli command "keys *" or "scan 0"  returning empty set or list as shown in following

_127.0.0.1:6379> keys *_
_(empty list or set)_
_127.0.0.1:6379> keys *_
_(empty list or set)_
_127.0.0.1:6379> scan 0_
_1) "0"_
_2) (empty list or set)_
_127.0.0.1:6379>_

After users were authenticated, spring session was created in redis, but XSRF-TOKEN seemed expired and got a brand new one as **23ca421d-5273-4fab-a048-266a60bf9df5**
 
Examining redis hash associated with spring session(7f73ff6b-906d-4b8b-970f-65044d1a3180),  I could not find something matching XSRF-TOKEN as  23ca421d-5273-4fab-a048-266a60bf9df5

127.0.0.1:6379> HSCAN spring:session:sessions:7f73ff6b-906d-4b8b-970f-65044d1a3180 0 COUNT 1000
1) "0"
2) 1) "creationTime"
   2) "\xac\xed\x00\x05sr\x00\x0ejava.lang.Long;\x8b\xe4\x90\xcc\x8f#\xdf\x02\x00\x01J\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\x01^\x06\xba/4"
   3) "lastAccessedTime"
   4) "\xac\xed\x00\x05sr\x00\x0ejava.lang.Long;\x8b\xe4\x90\xcc\x8f#\xdf\x02\x00\x01J\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\x01^\x06\xbaa\xa7"
   5) "maxInactiveInterval"
   6) "\xac\xed\x00\x05sr\x00\x11java.lang.Integer\x12\xe2\xa0\xa4\xf7\x81\x878\x02\x00\x01I\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\a\b"
   7) "sessionAttr:SPRING_SECURITY_CONTEXT"
   8) "\xac\xed\x00\x05sr\x00=org.springframework.security.core.context.SecurityContextImpl\x00\x00\x00\x00\x00\x00\x01\xa4\x02\x00\x01L\x00\x0eauthenticationt\x002Lorg/springframework/security/core/Authentication;xpsr\x00Oorg.springframework.security.authentication.UsernamePasswordAuthenticationToken\x00\x00\x00\x00\x00\x00\x01\xa4\x02\x00\x02L\x00\x0bcredentialst\x00\x12Ljava/lang/Object;L\x00\tprincipalq\x00~\x00\x04xr\x00Gorg.springframework.security.authentication.AbstractAuthenticationToken\xd3\xaa(~nGd\x0e\x02\x00\x03Z\x00\rauthenticatedL\x00\x0bauthoritiest\x00\x16Ljava/util/Collection;L\x00\adetailsq\x00~\x00\x04xp\x01sr\x00&java.util.Collections$UnmodifiableList\xfc\x0f%1\xb5\xec\x8e\x10\x02\x00\x01L\x00\x04listt\x00\x10Ljava/util/List;xr\x00,java.util.Collections$UnmodifiableCollection\x19B\x00\x80\xcb^\xf7\x1e\x02\x00\x01L\x00\x01cq\x00~\x00\x06xpsr\x00\x13java.util.ArrayListx\x81\xd2\x1d\x99\xc7a\x9d\x03\x00\x01I\x00\x04sizexp\x00\x00\x00\x01w\x04\x00\x00\x00\x01sr\x00Borg.springframework.security.core.authority.SimpleGrantedAuthority\x00\x00\x00\x00\x00\x00\x01\xa4\x02\x00\x01L\x00\x04rolet\x00\x12Ljava/lang/String;xpt\x00\tROLE_USERxq\x00~\x00\rsr\x00Horg.springframework.security.web.authentication.WebAuthenticationDetails\x00\x00\x00\x00\x00\x00\x01\xa4\x02\x00\x02L\x00\rremoteAddressq\x00~\x00\x0fL\x00\tsessionIdq\x00~\x00\x0fxpt\x00\x0f0:0:0:0:0:0:0:1ppsr\x002org.springframework.security.core.userdetails.User\x00\x00\x00\x00\x00\x00\x01\xa4\x02\x00\aZ\x00\x11accountNonExpiredZ\x00\x10accountNonLockedZ\x00\x15credentialsNonExpiredZ\x00\aenabledL\x00\x0bauthoritiest\x00\x0fLjava/util/Set;L\x00\bpasswordq\x00~\x00\x0fL\x00\busernameq\x00~\x00\x0fxp\x01\x01\x01\x01sr\x00%java.util.Collections$UnmodifiableSet\x80\x1d\x92\xd1\x8f\x9b\x80U\x02\x00\x00xq\x00~\x00\nsr\x00\x11java.util.TreeSet\xdd\x98P\x93\x95\xed\x87[\x03\x00\x00xpsr\x00Forg.springframework.security.core.userdetails.User$AuthorityComparator\x00\x00\x00\x00\x00\x00\x01\xa4\x02\x00\x00xpw\x04\x00\x00\x00\x01q\x00~\x00\x10xpt\x00\x04user"
127.0.0.1:6379>

Thanks
Ming Qin

**Comment by dsyer** [comment]
OK, I understand the question now (not that I get why you want to reverse engineer the session storage). But in this guide we don't use session storage for the csrf token. I guess that's a mistake in the text, which led us both down this alley. I'll see about fixing that.

**Comment by mingqin1** [comment]
Dave:
  Thanks for your efforts to this series tutorials. In the efforts of storing csrf token in redis, If I can help something , please not hesitate to ask.  I forked the this tutorial to my github account as well.  
Ming Qin

**Comment by irefaat** [comment]
Hello @dsyer 

Thanks a lot for your support.

Would you please confirm if Spring Session (Redis) will include the CSRF token when using Reactive WebFlux "CookieServerCsrfTokenRepository" ?

Thanks a lot.
