### ISSUE TITLE
oauth2-logout project (AuthserverApplication)-Missing Apporval Page For Getting Authorization Code 

### ISSUE THREAD

**Issue by mingqin1** [spring-guides/tut-spring-security-and-angular-js#159]
Hi:
  When generating an authorization code by visiting the authorization endpoint at -http://localhost:9999/uaa/oauth/authorize?response_type=code&client_id=acme&redirect_uri=http://example.com , the approval page is missed, though authorization code was generated.
 Same test applied to oauth2 project,  approval page is right. see following picture
![missing approval page on authserver](https://user-images.githubusercontent.com/6629272/29990830-44061888-8f33-11e7-95b0-b4fb2b9471cc.JPG)

**Comment by dsyer** [comment]
That was by design. Read the text and look in the source code for autoapprove.

**Comment by mingqin1** [comment]
Hi Dave:
 thanks
