### ISSUE TITLE
CORS should be "Cross Origin" not "Common Origin"

### ISSUE THREAD

**Issue by gregturn** [spring-guides/tut-spring-security-and-angular-js#16]
See https://github.com/spring-guides/tut-spring-security-and-angular-js/issues/1 via @hantsy

**Comment by hantsy** [comment]
There is still a term(Common origin) existed in **double** adoc.
[https://github.com/dsyer/spring-security-angular/tree/master/double](https://github.com/dsyer/spring-security-angular/tree/master/double)

**Comment by hantsy** [comment]
@dsyer  @gregturn  Thanks.
