### ISSUE TITLE
Update for Angular 2-4? (Not AngularJS)

### ISSUE THREAD

**Issue by MaximeBelanger** [spring-guides/tut-spring-security-and-angular-js#162]
Any plans for an update to this (great) guide for an Angular 4 project?
I am starting a new Spring Boot (Rest, Security, JPA) project based on this blog, using the latest Angular for the frontend, and some of the code doesn't work anymore. (ng-cloak, for example ).

**Comment by dsyer** [comment]
I have made a few attempts to do that, but Angular now is completely tied to npm which we explicitly didn't want to use in these guides, so I haven't found a Java friendly way to do it that. I might reconsider, so pull requests with suggestions would be helpful.

**Comment by dsyer** [comment]
Master branch is now Angular (4). The old code is marked as a branch in github called "angularjs".

**Comment by MaximeBelanger** [comment]
Thanks for the update! A suggestion: You might want to rename the tutorial "/tut-spring-security-and-angular", because using angular-js explicitely in the tutorial name might turn away some Google searches for "Spring security" and Angular. I mostly ignore anything with "AngularJS" in the page titles now, and I know a lot of people do that too.

**Comment by dsyer** [comment]
I know, but we’d have to set up redirects to the old address. Doesn’t seem worth it.
