### ISSUE TITLE
angular.module (angular is not defined) 

### ISSUE THREAD

**Issue by RfanKD** [spring-guides/tut-spring-security-and-angular-js#164]
Thank you for the thorough explanation!
But when I try to run even the basic application
I would get the error " angular is not defined "

This is run from Spring Tool Suite. Is there a missing configuration link ?

**Comment by dsyer** [comment]
If you build on the command line first it will work. There is also an m2e extension for wro4j that works for me in Eclipse (it’s probably discovered and selected for you by a quick fix.
