### ISSUE TITLE
Move the login page to the ui module

### ISSUE THREAD

**Issue by demetrio345** [spring-guides/tut-spring-security-and-angular-js#165]
I have a question, how can I move the login page to the UI module any topic to read to understand how to implement this. An also how to provide the login entrypoint to an android and iOs application?

**Comment by dsyer** [comment]
Sorry, you'll have to clarify a bit. Most of the UI modules in the samples have a login page already.

**Comment by demetrio345** [comment]
Thanks for the fast answer, in the Oauth2 with JWT sample, I'm trying to move the login page(that is actually on the auth module) to the UI module.

**Comment by dsyer** [comment]
That doesn't make any sense. The whole point of OAuth2 is to delegate that to an external service. How would the auth server authenticate the user without a login page?

**Comment by demetrio345** [comment]
Ok I understand that. I was trying to move only the capture of the user and password, so I could have the login page on the UI server without removing the login page on the auth server. I was trying to do this, to understand how to implement the login on an android or iOS app.

**Comment by dsyer** [comment]
I still don't understand your proposed flow. Seems like you don't want to use OAuth actually (which is fine).
