### ISSUE TITLE
Authentication using social login provider like Facebook or Google with JWT token 

### ISSUE THREAD

**Issue by anandk2907** [spring-guides/tut-spring-security-and-angular-js#168]
I am implementing a similar use case at my workplace, but there is a small difference. I want to authenticate using Facebook or Google, but pass the JWT token to the UI (ZUUL) and resources (API) instead of using the UserInfoUri endpoints. Is it possible to do it? In this example the user is authenticated by in-memory authentication and pass the JWT to UI and resources, I would like to use an option where users can use the Facebook or google to get authenticated and then Pass the JWT token to the UI and resources to access it. Any suggestion or examples will be helpful. Thanks in advance

**Comment by dsyer** [comment]
Spring Boot (up to 1.5) has support for JWT, and one of the samples in this guide shows you how to do it. There’s another tutorial specifically about Facebook and Github authentication. You should be able to join the dots.

**Comment by anandk2907** [comment]
Thanks for the quick response.
And yes I checked that tutorial but the authentication is done by using UserInfoUri endpoint and not by the JWT token. I guess you mean this tutorial-https://spring.io/guides/tutorials/spring-boot-oauth2/#_social_login_simple

**Comment by dsyer** [comment]
Yes, I meant that one. It has the social bits and this one has the JWT bits. I did say you'd have to join the dots.

**Comment by anandk2907** [comment]
Thanks!!
I figured it out and it works perfectly now, although it took me a while to get it done. Thanks for all your help and support.
