### ISSUE TITLE
Missing base href in "The login page" part of tutorial

### ISSUE THREAD

**Issue by mikolajmazur** [spring-guides/tut-spring-security-and-angular-js#169]
Hello
after adding router to the application it's not mentioned anywhere in this part of the tutorial that you need to add <base href="/"> to the head section of index.html file in order for the application to actually work. It is however included in the index.html file in repository so code sample in repository works fine.

Also some of the html files don't load correctly in readme ("app.html" in "Add Navigation to the Home Page", "home.html" in "The Greeting", "login.html" in "The Login Form").

I'm talking about the section of the tutorial that's in the 'single' folder.

**Comment by dsyer** [comment]
Fixed the `<base/>` thing, thanks. Not sure what you mean by "load correctly". It all looks fine here to me: https://spring.io/guides/tutorials/spring-security-and-angular-js/.
