### ISSUE TITLE
Logout doesn't work if we change localhost for 127.0.0.1

### ISSUE THREAD

**Issue by demetrio345** [spring-guides/tut-spring-security-and-angular-js#172]
Hi All,
I'm working with the logout implementation explained here:
https://spring.io/guides/tutorials/spring-security-and-angular-js/#_oauth2_logout_angular_js_and_spring_security_part_ix

It works fine, but when I change the URI on the post call from http://localhost:9090 to http://127.0.0.1:9090, stops working, anyone know if there is an additional configuration to make this works.

**Comment by dsyer** [comment]
None of the apps in this tutorial run on port 9090 AFAIK. Can you be a bit more specific about what you did and what doesn’t work?

**Comment by demetrio345** [comment]
My mistake, is on the 9999 port.

I'm changing the POST url on the angular script from http://localhost:9999/uaa/logout to http://127.0.0.1:9999/uaa/logout

After this change, the logout doesn't work, but all the request has the same http response. It seems that logouts from the UI server but not from the authentication server.
I'm doing this because I face this problem when I deployed the application on a server and start to use the server address instead of localhost.

**Comment by dsyer** [comment]
The cookie for the session is probably tied to the hostname (it came from the authorization uri that you configured in application.yml).

**Comment by demetrio345** [comment]
OK, I made this change and it works if I access to the UI via 127.0.0.1:8080, but if I access using localhost:8080 it fails too. I suppose that is for the same reason.
Is there a way to avoid this? I'm thinking that I will face problems, because I would deploy the UI and the Auth app on different servers.

**Comment by dsyer** [comment]
I don’t understand the question. The UI and auth server are already on different “servers” (different ports and paths). If you actually try something that doesn’t work, can you be a bit more specific please?

**Comment by demetrio345** [comment]
Hi Dave, you are right, the only problem that I was having it was related to the session cookie that you mentioned. Thank you.
