### ISSUE TITLE
Changes to use a symmetric key on the JwtAccessTokenConverter of oauth2 vanilla project

### ISSUE THREAD

**Issue by demetrio345** [spring-guides/tut-spring-security-and-angular-js#173]
Hi Dave,

I'm making changes to use a symmetric key on the JwtAccessTokenConverter on the authserver:
```

@Bean
	public JwtAccessTokenConverter jwtAccessTokenConverter() {
		JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
		converter.setSigningKey("123");
		return converter;
	}
```

After that I add the same converter on the resource server and both servers works(I can make request via Postman), but I cannot make it work with the ui server.
I tried to add the key-uri on the .yml file of ui server, but doesn't work:
```
resource:
      jwt:
        key-uri: http://localhost:9999/BCM/uaa/oauth/token_key
```

this URI gives the next response:
`{"alg":"HMACSHA256","value":"123"}`

I also tried to put the security.oauth2.resource.jwt.key-value as "123" on the yml, without success.

Any idea on how to make the UI work?

**Comment by dsyer** [comment]
Setting `security.oauth2.resource.jwt.key-value` should work, as long as you don’t set some other property that makes it redundant.
