### ISSUE TITLE
Folder content for double/gateway seems incorrect

### ISSUE THREAD

**Issue by colosistech** [spring-guides/tut-spring-security-and-angular-js#174]
Hi Dave,
Thanks for detailed tutorial & repository. I was going through it and noticed that Section 6 (Multiple UI Applications and a Gateway) of the tutorial 
[https://spring.io/guides/tutorials/spring-security-and-angular-js/#_multiple_ui_applications_and_a_gateway_single_page_application_with_spring_and_angular_js_part_vi](url) 
have references to /double project of this github repository. Here, the gateway sub-folder should have Java project (with zuul and security configurations), but gateway folder contains angular code. 

I'm sorry if I am missing something, kindly help!

**Comment by dsyer** [comment]
I see a zuul proxy (https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/double/gateway/src/main/java/demo/GatewayApplication.java#L26). What's the problem?

**Comment by colosistech** [comment]
got it, it was error at my end.
