### ISSUE TITLE
How does the application knows about the login and password

### ISSUE THREAD

**Issue by avi613** [spring-guides/tut-spring-security-and-angular-js#183]
I have a question that puzzles me:

In the very begining of this tutorial, _A Secure Single Page Application_, there seems to be a dialog between the Front End and the Back End, where the user is never promped on for a login and password. Yet there seems to be some magic at some point where you say that the header of the `GET` query on `"/resource"` should contain:

```
Authorization: Basic dXNlcjpwYXNzd29yZA==
```

which is no more that the base 64 encoded for `user:password`

> The browser is sending the username and password with every request (so remember to use HTTPS exclusively in production). There’s nothing "Angular" about that, so it works with your JavaScript framework or non-framework of choice.

**How can the browser possibly know about the login and password of the user when it was not typed in by the user?**

**Comment by dsyer** [comment]
It's a standard browser feature. It caches and re-uses basic authentication (per host).

**Comment by avi613** [comment]
You mean because both the FE and BE are on `http://localhost:8080`?

**Comment by dsyer** [comment]
Sort of. There is no FE/BE in the basic sample, just a Spring Boot application.

**Comment by avi613** [comment]
I'm only talking about basic-auth

**Comment by avi613** [comment]
OK for the _non-authenticated_ bit. It was awkward.

What I mean is that, my FE runs on `http://localhost:4200` and my BE runs on `http://localhost:8080`.

I successfuly authenticate by sending my credentials in the header to `http://localhost:8080/user`. Then I can retrieve the current user.

Next thing I know, I'm trying to fetch the resource but, of course, I don't send my credentials again when I `GET` on `http://localhost:8080/resource`. At this point, the **query fails**.

What I'm trying to understand is:
 * is that completely normal?
 * should it work in this case also?

**Comment by dsyer** [comment]
Yes, it's normal. No it shouldn't "just work". With 2 separate servers you need a strategy for propagating the authentication. Since that is most of the point of this tutorial I suggest you go and read it all before you ask more questions. Look at the vanilla and proxy samples for instance.

**Comment by avi613** [comment]
So I have been pushing this tutorial further. But I don't have Redis, and by no means able to get it. I understand that Redis is the magic glue that passes the token from one app to the other.

Is there another way to pass on the token?

I mean just using plain Spring (which is enough dependencies...)

**Comment by dsyer** [comment]
Redis is really ridiculously easy to install and use (there's a docker-compose.yml in the samples). If you can't use it, you have other choices in Spring Session (read the docs). Or move onto the oauth2 samples.

**Comment by avi613** [comment]
I am super restricted in terms of dependencies. Docker and Oauth2, for instances are not going to be in house before long.
I guess I'll dwell on Spring Session's doc a bit.
