### ISSUE TITLE
Getting a 401 and 404 error

### ISSUE THREAD

**Issue by Lempkin** [spring-guides/tut-spring-security-and-angular-js#189]
Hi,

I've checkout the project and run it, but it doesn't work for me, in console I have this in console : 

![error2](https://user-images.githubusercontent.com/10230485/47266854-583dcf80-d53c-11e8-8110-ad5efd3ad808.png)

Do I have to do something except checkout and run project?
Thx

**Comment by dsyer** [comment]
You didn't really say what you did. There are several samples here, and most of them require you to run more than one JVM. Can you publish some steps to reproduce, please?

**Comment by Lempkin** [comment]
Actually it seems that problem was that I ran all project (UI as well) with the STS eclipse plugin, and this way, the angular part seems to be not reachable. If I boot the UI part with classic MVN this is working
