### ISSUE TITLE
Single - CSRF protection does not kick - "help wanted" 

### ISSUE THREAD

**Issue by dincau33** [spring-guides/tut-spring-security-and-angular-js#20]
Hello everybody,

I am following Part II - The Login Page tutorial step by step. I am at the stage where CSRF protection is not configured ("Handling the Login Request on the Server" section on the webpage https://spring.io/guides/tutorials/spring-security-and-angular-js/#_the_login_page_angular_js_and_spring_security_part_ii) however the application is working perfectly well and I don't face 403 status when I submit login page. I don't understand why. I am able to access all the resources. It seems CSRF spring security protection does not kick.

I have clone the git repository and my java class look like that

@SpringBootApplication
@RestController
public class UiApplication {

  ...

  @Configuration
  @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
  protected static class SecurityConfiguration extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
      http
        .httpBasic()
      .and()
        .authorizeRequests()
          .antMatchers("/index.html", "/home.html", "/login.html", "/").permitAll()
          .anyRequest().authenticated();
    }
  }

}

It would be much appreciated if you have any idea 

thanks

Bye

Benoit

**Comment by dsyer** [comment]
CSRF protection is only needed for state changes (e.g. HTTP POST). The app is so simple at this stage there are no POSTs (except logout).

**Comment by jjromannet** [comment]
Hello dsyer, 

Thanks for the explanation. However I would like to point that the contents of the tutorial are a bit misleading. It says:
"The application is almost ready to use, but if you try running it you will find that the login form doesn’t work. Look at the responses in the browser and you will see why:" 

Which as you pointed is not true as at this point application is not doing any post requests.
And the logout function has not been yet introduced (at this point in the tutorial)

Regards
Jan

BTW Many thanks for the great tutorial!

**Comment by dincau33** [comment]
Hello Dsyer,

Thanks for the explanation and the great tutorial.

Regards
Benoit
