### ISSUE TITLE
Gateway login page

### ISSUE THREAD

**Issue by probertf** [spring-guides/tut-spring-security-and-angular-js#202]
Is it possible to use in the GATEWAY a login page loaded from UI? The pros would be that you don't have to duplicate all the css/images in both UI and GATEWAY.

**Comment by dsyer** [comment]
There are many ways to skin that cat. I'm not sure any of them are really in scope for this guide, but you can find some discussion here: https://github.com/spring-cloud/spring-cloud-gateway/issues/29.

**Comment by probertf** [comment]
Too many, I'd say :). Thank you for the link. Since my UI is angular, I will explore ng-include. Another option would be to redirect /login from GATEWAY to something like /ui/angular-login/. 
I can close this, i suppose.
