### ISSUE TITLE
oauth2 - No Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by fiallega** [spring-guides/tut-spring-security-and-angular-js#21]
In the oauth2 project, when I run the outh2-ui, I get in the browser the following cross domain error: 

XMLHttpRequest cannot load http://localhost:9999/uaa/oauth/authorize?client_id=acme&redirect_uri=http://localhost:8080/login&response_type=code&state=9EMa0U. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

But when you hit the "login" button you don't get it and you make it all the way to http://localhost:9999/uaa/login in order to authenticate which is the desired behavior.

Taking a look at the Network  view in Chrome, the difference is that when the app loads the http://localhost:9999/uaa/oauth/authorize request shows as the initiator "other", but when you click on the login button the initiator shows as localhost:8080/login

**Comment by dsyer** [comment]
That's not really an issue. The AJAX client can't follow the redirects but the browser can. It doesn't affect the user experience.
