### ISSUE TITLE
404 after login in basic

### ISSUE THREAD

**Issue by jmdopereiro** [spring-guides/tut-spring-security-and-angular-js#229]
Hello, I just cloned and run the UiApplication of the basic module, on http://localhost:8080 I get the login prompt but after I type the user/password credentials I get a 404.

Please help

Thanks

![image](https://user-images.githubusercontent.com/7406837/73386569-57fbba80-42cf-11ea-864c-227c41b08fb7.png)

![image](https://user-images.githubusercontent.com/7406837/73386719-a4df9100-42cf-11ea-9d84-15ddfe593243.png)

![image](https://user-images.githubusercontent.com/7406837/73386760-b7f26100-42cf-11ea-8656-1f27ffb8a81e.png)

**Comment by havinhphu188** [comment]
Have you solve the issue? I have encountered the same problem

**Comment by jmdopereiro** [comment]
Hello, yes. I was having the issue when running the @SpringBootApplication class from the IntelliJ IDE. 

When running with maven everything works fine.

`mvn spring-boot:run`

This link explains in more detail:

https://github.com/spring-projects/spring-boot/issues/9371

**Comment by havinhphu188** [comment]
Thank you very much
