### ISSUE TITLE
Logout is not working in project 'single'

### ISSUE THREAD

**Issue by tamaro-skaljic** [spring-guides/tut-spring-security-and-angular-js#231]
The logout is not working properly. When you click on the button, the singlepage application tells you that you are logged out, but when you reload the page, you are logged in again. Even if you access /user or /resource, you won't get a 401 error.

Is that supposed to happen?

**Comment by tamaro-skaljic** [comment]
I just tried to reproduce it again and I noticed that it works fine if you log in via the singlepage application. Now I was wondering if I'm stupid or why it didn't work then.

To reproduce it, you have to go to `/resource` or `/user` with your browser once... There the browser popup opens (I thought it was blocked?), where you can also log in and if you log in via it, the logout via the singlepage application doesn't work anymore.

**Comment by dsyer** [comment]
That seems like the expected behaviour. There is a section in the guide about logout I think.
