### ISSUE TITLE
Can't set a user password using application.properties

### ISSUE THREAD

**Issue by BeaRRRRR** [spring-guides/tut-spring-security-and-angular-js#235]
In the basic README, it is said that I could set the user password, to not scrape the console.log for the password every time.

> TIP: If you don't like scraping the console log for the password just add this to the "application.properties" (in "src/main/resources"): `security.user.password=password` (and choose your own password). We did this in the sample code using "application.yml".

But for some reason, it didn't work for me, the password wasn't setting and still I had to look for it in the console output. What worked for me though, was `spring.security.user.password=password`, there isn't a world of difference, but as I'm coming back to spring after a while it took me some time to come to that solution, so new users might also struggle with it for some time. I suggest changing the README a bit, to something like that:

> TIP: If you don't like scraping the console log for the password just add this to the "application.properties" (in "src/main/resources"): `security.user.password=password` (and choose your own password). We did this in the sample code using "application.yml". If `security.user.password=password` didn't work for you, try `spring.security.user.password=password`.

I don't know why `security.user.password=password` didn't work for me so here is my system info:
OS - Manjaro Linux
Kernel - 4.19.118-1-MANJARO
Java - 1.8
Spring Boot - 2.2.6.RELEASE

P.S. I can create a PR, or provide a minimal reproducible repo if you want ;)

**Comment by marcello-dev** [comment]
Try to set `spring.security.user.password=password`. In this tutorial they use the version 1.5.10.RELEASE of spring-boot. You are using 2.2.6.RELESE and I think at some point Spring decided to include the "spring." prefix for the security properties.

**Comment by marcello-dev** [comment]
Actually in the branch "boot2" you find the correct property. [Here](https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/boot2/single/src/main/resources/application.yml#L1)
