### ISSUE TITLE
package org.springframework.session.web.http does not exist

### ISSUE THREAD

**Issue by MertalpTasdelen** [spring-guides/tut-spring-security-and-angular-js#237]
Hello all,

I am trying to achieve part sprint-session. Code block

```
	@Bean
	HeaderHttpSessionStrategy sessionStrategy() {
		return new HeaderHttpSessionStrategy();
	}
```

does not recognize by my app. When I used dependency
```
<dependency>
    <groupId>org.springframework.session</groupId>
    <artifactId>spring-session</artifactId>
    <version>1.3.5.RELEASE</version>
</dependency>
```

It will go away but this time I get
**No session repository could be auto-configured, check your configuration (session store type is 'redis')** error.
What am I missing? Or anything changes?

**Comment by ArchaneZakaria** [comment]
did you fix the problem ?
