### ISSUE TITLE
SSO autologin not works

### ISSUE THREAD

**Issue by szabobar** [spring-guides/tut-spring-security-and-angular-js#24]
First of all, thanks for the very good articles, and samples.

My problem in oauth2 sample:
I can start all 3 application, and everything works fine, but:
I would like to test, what happens, if the UI project cookie expires, but AuthServer's not. 
In my case, if the authserver thinks, that user is logged in, but UI has not got logged in information, then UI fetch that information from AuthServer. But not did it.

How can I tried this:
- Login to UI, with Authserver's help (got cookie session for Authserver, and UI also)
- delete/invalidate ui cookie
- refresh the page

Result:
- I need to reLogin, but in Authserver I am logged in, so I can not reEnter my username, and password)

Expected result:
- The UI server auto login the user (SSO), and display the page, as u logged in, and authorized. (not neccesary to click to login link, and trust again)

**Comment by dsyer** [comment]
The vanilla oauth2 sample does not issue cookies from the auth server so it is possible that is the problem. You can set `security.sessions=if-required` to ensure you get a cookie.
