### ISSUE TITLE
Deploy it on tomcat

### ISSUE THREAD

**Issue by jbarros35** [spring-guides/tut-spring-security-and-angular-js#25]
Hi, I checkout the source code, tried build a project using maven and Eclipse, after tried run it inside a Tomcat. It cannot run stand alone as every developer in the world does, please can you convert it to a normal form? Many of us don't appreciate running command line and wait things happen magically.

**Comment by paboulos** [comment]
This page has the info you're looking for: http://spring.io/guides/gs/convert-jar-to-war/

**Comment by dsyer** [comment]
You also don't need a command line. If you have the code in Eclipse just click on the main method and select "Run As -> Java Application". It's way easier than deploying to Tomcat.
