### ISSUE TITLE
Only web static front ui angular application?

### ISSUE THREAD

**Issue by leordev** [spring-guides/tut-spring-security-and-angular-js#26]
Hello gurus! 

I could not find a model where the front ui application is only static files, like a pure angular app that just consume the backend. This is a bad practice? 

Nowadays there's a lot of services in cloud on this model: static angular app -> firebase etc.

So I was thinking to do that with the OAuth2 model.

There's a good reference of Angular Consumption (just ignores the rails part): http://angular-tips.com/blog/2014/05/json-web-tokens-examples/

**Comment by dsyer** [comment]
I'm not sure if this is a question (or what the question is). All the apps in this repo have UIs with static resources. Could you explain a bit?
