### ISSUE TITLE
Introduction to CSRF is confusing

### ISSUE THREAD

**Issue by cbeams** [spring-guides/tut-spring-security-and-angular-js#3]
From https://spring.io/guides/tutorials/spring-security-and-angular-js#_csrf_protection:

> The application is almost ready to use, but if you try running it you will find that the login form doesn’t work. Look at the responses in the browser and you will see why:
>
>    
>    POST /login HTTP/1.1
>    ...
>    Content-Type: application/x-www-form-urlencoded
>    
>    username=user&password=password
>    
>    HTTP/1.1 403 Forbidden
>    [...]

This is inaccurate. If one follows the instructions up to this point in the tutorial, they'll actually still be requesting the `/user` resource with a GET. This returns 200, not 403.

The tutorial should instruct the reader to switch from GET to POST (and perhaps a bit about why), and then resume the conversation about CSRF/XSRF from there.

Otherwise, this tutorial is excellent. Many thanks @dsyer and @gregturn!

**Comment by cbeams** [comment]
Having worked my way a bit further through the tutorial, and double-checking [Dave's current source for the project](https://github.com/dsyer/spring-security-angular/blob/master/modular/src/main/resources/static/js/auth/auth.js#L32), I see the GET for /user is actually *not* intended to become a POST (which makes sense, given that we're still dealing with Basic HTTP auth).

So I am confused now as to which POST the tutorial was referring. The CSRF bits are obviously still important, but it seems out of place at this point in the tutorial given that the only XmlHttpRequest in play is (and should remain) a GET.

**Comment by dsyer** [comment]
It's a bug in the text is all. There used to be a POST, but really it's not necessary for this app (which is way too simple). Any real app would need to have POSTable endpoints, so the text should say so, but the text as it stands is out of step with the code. Thanks for pointing that out. (Some one already raised the issue with me in an email, but unless I'm missing something it's not in the source repo as an issue yet .) The source remains at https://github.com/dsyer/spring-security-angular, for now at least.

**Comment by dsyer** [comment]
Actually, I suppose a case could be made for POSTing to /user to authenticate, purely to ensure that the CSRF protection is in place. That's also an interesting change.

**Comment by cbeams** [comment]
Hey Dave. I was just coming back to note that handling /logout happens via a POST, and that's a natural enough place to encounter and resolve the CSRF issue.

**Comment by cbeams** [comment]
And I encountered another issue, by the way, with CSRF handling. Repro steps:

1. Follow the instructions to set up Spring Security for CSRF, setting the "XSRF"-flavored cooking, etc.
2. Follow the instructions to implement /logout handling
3. Log in, notice that this is successful.
4. Click elsewhere in the app (you'll see why this is important below)
5. Log out, and notice that this too is successful.
6. Log back in.
7. Without clicking anywhere else in the app, attempt to log out immediately. Notice that this fails, with the XHR request returning 403 and the following payload:

    {"timestamp":1434146160197,"status":403,"error":"Forbidden","message":"Expected CSRF token not found. Has your session expired?","path":"/signout"}

This happens because between steps 6 and 7, there hasn't been a chance for the `Set-Cookie: XSRF-TOKEN=...` header to be passed to the client. "Clicking around" the app in step 4 is a work-around, but of course a user should be free to log out immediately after logging in if for whatever reason he wants to.

To solve this problem in my own application, I simply issue one additional XHR (GET) request for `/user` in the callback passed to `authenticate` (if `$scope.authenticated` is `true` at that point). Doing this ensures that the XSRF-TOKEN cookie gets set, and I'm then free to log out immediately after logging in.

**Comment by dsyer** [comment]
Yeah, that's a bug (see the tracker for the source code for a less detailed description). But @rwinch said it was better to fix it inSpring Security so I didn't really spend a lot of time on it.

**Comment by dsyer** [comment]
The ordering of the text has changed so we add an actual POST before explaining and adding CSRF. Can you raise another issue for the cookie thing or watch this one: https://github.com/dsyer/spring-security-angular/issues/15? Thanks.
