### ISSUE TITLE
oauth2 two factor(multifactor) authorization

### ISSUE THREAD

**Issue by tortik** [spring-guides/tut-spring-security-and-angular-js#35]
Hi. Could you please help me? I want to implement 2FA authorization with oauth2. 
I want to use grant_type: password. 
How do I see it... 
Client after input login/password, will receive token with PRE_AUTH role. On success authentication I will add listener which will call service for sending sms with some code. I should add second factor here... I want to enhance token, or base on old token and sms code generate new token with FULL role.... I use default pass for oauth/token, but when I want to call it with Authentication: bearer token, I receive 403. 
I think I should add Filter somewhere for intercept request, extract and parse token, add new role(FULL) and generate new token. 
But where should I add this Filter? 
And how should I generate new token, based on old one, If I use default bearer? 
I need just entry points. 
Maybe you have better solution how should I implement 2FA with oauth2. 
Thanks in advance.

**Comment by dsyer** [comment]
I think you should use auth code grants for 2FA (there's a web interface that you can use to accept the token etc.).
