### ISSUE TITLE
How to request user authentication once a user signs out and signs in again?

### ISSUE THREAD

**Issue by ghost** [spring-guides/tut-spring-security-and-angular-js#37]
Once a user clicks on logout, the UI Server is logging out, but once again if login is clicked it is automatically authenticating the user, how to discard the earlier authentication and force user authentication once again in this scenario?

**Comment by dsyer** [comment]
Which app are you using? It works for me with all the apps that have a login page.

**Comment by alexSaraivaM** [comment]
i'm having the same problem, i'm using modular app... how to make an login page on it?

**Comment by dsyer** [comment]
There's a sample app called "single" that adds a login page to an existing app. It's covered extensively in the tutorial that goes with this project.
