### ISSUE TITLE
wro4j not working

### ISSUE THREAD

**Issue by LeonardLaszlo** [spring-guides/tut-spring-security-and-angular-js#42]
Hello!

I am learning spring and while following your [spring security and angular js ](http://spring.io/guides/tutorials/spring-security-and-angular-js/) tutorial I found a bug.

The problem: wro4j does not generate the css and js files.
![Screenshot](http://www.kephost.com/images/2015/10/15/ScreenShot2015-10-15at16.38.56.png)

Please help me to solve this problem!

**Comment by dsyer** [comment]
Did you build the project from the command line? In an IDE? how?

**Comment by LeonardLaszlo** [comment]
I've built it with IntelliJ IDEA

**Comment by dsyer** [comment]
I don't know if IDEA has any tooling for wro4j. I guess you have to build with Maven and make sure the generated resources are on the classpath (it will probably require some configuration in your IDE project).

**Comment by LeonardLaszlo** [comment]
I think there is something wrong in the pom.xml file because the wro4j external library is not imported.
![alma](http://www.kephost.com/images/2015/10/20/ScreenShot2015-10-20at21.55.22.png)

**Comment by dsyer** [comment]
I don't use IDEA  so I really don't know what you are showing me. The wro4j tool is being used as a plugin in this project though, so it isn't supposed to be on the classpath. When you build from the command line do you see CSS and JS in `target/generated-resources`?

**Comment by LeonardLaszlo** [comment]
when I run it from command line it works as expected :-)
