### ISSUE TITLE
Multiple UI:s, Zuul, Oauth2 SSO

### ISSUE THREAD

**Issue by flindby** [spring-guides/tut-spring-security-and-angular-js#43]
Hi Dave,

I'm trying to build something similar to your excellent tutorial "Multiple UI Applications and a Gateway" (double) in combination with "SSO with OAuth2: Angular JS and Spring Security Part V" (oauth2-vanilla).

Basically I want the architecture as in the project double, but protected with OAuth2 SSO instead of HttpSession.

My target is to have 3 completly different UI-applications (Spring boot / angular) behind a ZuulProxy. Each UI-application is annotated with @EnableOAuth2Sso, so the authentication is handled by a OAuth2 AuthorizationServer (authorization_code flow), login page at "/uaa/login".

I also have several resource servers that should be accessible by the UI-applications and also other clients (mobile apps etc). The resource servers and the authorization server share a TokenStore, so the access-tokens can be verified.

Questions/problems:
1. First and foremost; do you think my target architecture makes sense, or should I do some rethinking about some parts?
2. When I navigate to http://localhost:8080/ui1 (which is routed by zuul to http://localhost:8081) the browser can't load java-script files for ui1 application (it tries to get them from http://localhost:8080/js), only if I add an extra slash, i.e: http://localhost:8080/ui1/. What can be the reason for that?
3. When I navigate to http://localhost:8080/ui1/ and click on "login" I get redirected to http://localhost:9999/uaa/login as expected. But when I enter my credentials and sign-in I get redirected back to http://localhost:8081/#/ instead of :8080. How can I configure the setup to be redirected to the gateway as I think should be the intended scenario?

I created a sample repository for the applications, with only one UI. Please have a look.
https://github.com/flindby/spring-oauth2-zuul

**Comment by flindby** [comment]
@dsyer: 
For question number 2 I found another related issue here: (https://github.com/spring-cloud/spring-cloud-netflix/issues/454). I look into it in more detail over there.

For question number 3 I have some more detail:
1. When I hit /login for the ui1 client I get redirected to http://localhost:9999/uaa/login as expected. With Response Headers Location: http://localhost:9999/uaa/oauth/authorize?client_id=ui1&redirect_uri=http://localhost:8080/ui1/login&response_type=code&state=1234state
2. When I login I get redirected to http://localhost:8080/ui1/login?code=05TYHf&state=Q7gQjN and the Response Header Location is now http://localhost:8081/. I guess this is the problem. How can I configure Zuul/ui1 so that the location header is http://localhost:8080/ui1/ instead. Or do you see another problem with this intended scenario?

**Comment by khauser** [comment]
Dave wrote somewhere that the redirect is done by the security integration of your gateway (`compile("org.springframework.security.oauth:spring-security-oauth2")`).

I am also playing a little bit around separating the gateway from the authserver. My current state is to rewrite the request header by running the following class:

```
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import com.netflix.util.Pair;
import com.netflix.zuul.ZuulFilter;
import com.netflix.zuul.context.RequestContext;

public class ProxyReverseFilter extends ZuulFilter {

    private final String LOCATION_HEADER_NAME = "Location";

    @Override
    public String filterType() {
        return "post";
    }

    @Override
    public int filterOrder() {
        return 7;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() {
        RequestContext context = RequestContext.getCurrentContext();
        String portalHost = context.getRequest().getServerName();
        String portalProtocol = context.getRequest().getScheme();
        int portalPort = context.getRequest().getServerPort();
        List<Pair<String, String>> responseHeaders = context.getZuulResponseHeaders();
        for (Pair<String, String> entry: responseHeaders){
            if (entry.first().equals(LOCATION_HEADER_NAME) && !entry.second().equals(portalHost)) {
                try {
                    URL locationOriginal = new URL(entry.second());
                    String path = locationOriginal.getFile();
                    if (path.startsWith("/ui/"))
                        path = path.replace("/ui/", "/frontend/ui/");
                    else if (path.startsWith("/uaa/"))
                        path = path.replace("/uaa/", "/authserver/uaa/");
                    URL locationNew = new URL(portalProtocol, portalHost, portalPort, path);
                    entry.setSecond(locationNew.toString());

                    }catch(MalformedURLException e)
                    {
                        return new Object();
                    }
                }

            }

        return new Object();
    }

}
```

plus an bean entry in your Application:

```
    @Bean
    public ZuulFilter proxyReverseFilter(){
        return new ProxyReverseFilter();
    }
```

Also with a new route:

```
zuul:
  routes:
    authserver:
      path: /authserver/**
      url: http://localhost:7777
```

The gateway also needs an entry like this:

```
.antMatchers("/authserver/uaa/login", "/authserver/uaa/oauth/authorize").permitAll()
```

For your second question I would recommend to adjust also these matchers (maybe: `.antMatchers("/js").permitAll()`).

Maybe this could help..

@dsyer: Enhancing the first question of @flindby I would also be very interested in, whether such an architecture (without redirects to the authserver) makes sense (also in technical view with the code snippets above) or not?

**Comment by ddewaele** [comment]
@flindby : Hi , I realise this is an old thread, but I was wondering what your findings were with getting 
Zuul up and running for multiple UIs. I'm also trying to achieve SSO with Zuul / OAuth2 but can only do it with a single UI when running on the root path of Zuul. I looked at your repo and your UI was also mapped to /*\* 

```
zuul:  
  routes:    
    startpage:
      path: /**
      url: http://localhost:8081
```

So I assume this only works with 1 UI in that architecture.

Did you ever got a working solution with multiple UIs through Zuul (at different paths).

I've posted an [SO question](http://stackoverflow.com/questions/36100395/spring-security-oauth2-sso-with-zuul-proxy) for a similar architecture. Feel free to take a look.

Thx

**Comment by flindby** [comment]
@ddewaele : Hello, I never found that this architecture worked for me, so I decided to use Zuul at several places: as a api-gateway in front of my resource-services and in all my UI-applications. In my UI-applications I have a Zuul-route: "/api" which proxies to the API-gateway, and then the API-gateway proxies to the right resource-service. 

My API-Gateway has no OAuth2/security stuff, only the UI-applications has the "@EnableOauth2Sso" annotation. And then my resource-services authenticate/authorizes the access-tokens (JWTs).

And also.. In front of everything I have a Nginx Reverse Proxy, that proxis:
- https://api.company.com   -> Zuul API-Gateway
- https://accounts.company.com   -> Spring OAuth2 Authorization Server
- https://ui1.company.com  -> UI1 app, with Zuul and @EnableOAuth2Sso
- https://ui1.company.com  -> UI2 app, with Zuul and @EnableOAuth2Sso

I find this soultion quite flexible, but might be overkill. But I'm sure there exists a more neat/simple soloution.

**Comment by LeandroFChaves** [comment]
Hi!

Sorry for weak English and for reviving the topic, but come on ...

I have a situation very similar to the one you presented, but with some peculiarities. See if you can help me with any suggestions.

I have 3 UI applications in angular 7 and today all authenticate separately, I want to change this. Today, authentication is done using the grant flow password. I want to implement a single sign on for these 3 applications.

I started a study that can be analyzed in reposit https://github.com/LeandroFChaves/spring-security-oauth2 where I created a client, a resource and an authentication server. The idea is to create one more client, one resource server and both to authenticate in the oauth server with SSO, starting with the principle that if it was first logged in one while accessing the other client it will not have to log in again.

I thought of using the Zuul proxy to do this somehow, but I confess I'm lost.

My client already has a configured proxy that will point to some server that I imagined would be responsible for the single sing on with zuul, but I caught on that part.

As you have practically gone through the same situation, can you give any tips on how I can go on?

One important note is that my client is 100% javascript with angular, in most cases the situation is different.

Thank you.

Abs.
