### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by crimin3l** [spring-guides/tut-spring-security-and-angular-js#44]
Hi Dave,
Thank you for this amazing series and all the support you are giving us all.
My goal is building a stable, scalable and mostly as secure as it can get system based on microservices, with front ends both web and mobile (Android/IOS).
I have successfully integrated together the “double” and “oauth2” sample, with the authentication server version that uses JWT Tokens. So basically I have followed part VI of the series and went back to an external authentication server with JWT’s. I also use a different Docker Redis image that allows for setting a Redis password. With very little modifications the system is up and running, everything works as expected, except the logout functionality. 
I can login from the GW sith SSO, I can approve or deny request, etc. The problem is when I click the logout button, it logs me out at first. If I do a refresh of the page I am still logged out but at the second refresh something kicks in and I am automatically logged back in. 
I can see in the GW console at the second refresh the following:
Secure object: FilterInvocation: URL: /user; Attributes: [authenticated]
2015-11-18 12:09:34.469 DEBUG 3648 --- [io-8080-exec-10] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.oauth2.provider.OAuth2Authentication@e9fcae3d: Principal: user; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=0:0:0:0:0:0:0:1, sessionId=<SESSION>, tokenType=bearertokenValue=<TOKEN>; Granted Authorities: ROLE_ADMIN, ROLE_USER
2015-11-18 12:09:34.469 DEBUG 3648 --- [io-8080-exec-10] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@1488a3db, returned: 1
2015-11-18 12:09:34.469 DEBUG 3648 --- [io-8080-exec-10] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorization successful

Do you have any idea how to fix this? 
Thank you!

**Comment by dsyer** [comment]
Can you reproduce the issue with one of the existing samples (they all work for me)?

**Comment by crimin3l** [comment]
Hello Dave,
I was trying to do single sing off in the gateway. The idea is I am trying only to expose the GW to the internet and the rest of the system to be behind that GW with private addresses on different machines, not accessible from the outside world. Beside authentication, the REST calls from outside for resources also should go through this GW.
I have discovered that, after I click logout, if I open in browser localhost:8080/ui/logout or localhost:8081/logout i can actually log out and the log out is propagated in all apps. When I click login again it allows me to approve or deny in auth server without reentering credentials. 
If I want to revoke the credentials I have to first click logout, then open in browser 8081/logout then open in the browser localhost:9999/uaa/logout to get the full logout experience I want.
Now I need a way to do this programmatically. 
I guess what I should do is adapt the logout function to call this /logout endpoint in UI and the /logout endpoint in AUTH server from GW using post but I get access denied so I must either unsecure the /logout endpoints either send credentials in the post calls. 
What do you think? Is the above corect? Can this be done?
Thank you,
Stefan

**Comment by dsyer** [comment]
I didn't completely follow the architecture from your description, but it sounds like you have an auth server (the /uaa one) and the browser keeps a session with that server even after you logout from the main UI. This is normal. If you want to logout of the auth server as well you need to arrange for that to happen somewhere in your UI. It's not impossible, you just need to take care with CSRF tokens and stuff.

The harder problem is the "single sign off" for multiple UIs all controlled by the same central authentication. You can't really do that easily without making them all aware of each other, or making some other compromise (like a global cookie).

**Comment by crimin3l** [comment]
Thank you for the explanation, sounds like I am on the right track. I can live without single sign off for now.
Can you please give me an example of a angular $scope.logout function that can do a $http.post on the /logout endpoint that does the same thing as when i open in the browser localhost:8080/ui/logout considering that the UI endpoints are secured with auth and JWT token?
Thank you
