### ISSUE TITLE
Is it possible to restrict resource access on resource service with @PreAuthorize ?

### ISSUE THREAD

**Issue by vajda** [spring-guides/tut-spring-security-and-angular-js#47]
Hi, I have cloned your spring-security-angular/oauth2 example with resource, auth and ui components and tried to restrict resource endpoint with:

```
@PreAuthorize("hasAnyRole('ROLE_FOO','ROLE_BAR')")
@RequestMapping('/')
def home() {
    [id: UUID.randomUUID().toString(), content: 'Hello World']
}
```

however, it still passes (I expected 403 to be returned).
Is it possible to restrict resource access in a such way?

**Comment by dsyer** [comment]
To use `@PreAuthorize` you need to `@EnableGlobalMethodSecurity`.
