### ISSUE TITLE
Rest authentication

### ISSUE THREAD

**Issue by vajda** [spring-guides/tut-spring-security-and-angular-js#48]
As seen in examples, authentication is always done through web browser on authentication server. Is it possible to have security configuration in that way to do login in RESTful manner with oauth2? So, not to have redirect on server, but to get 401, and then do post on '/login' with username and password which will be sent to oauth server by zuul. And to have result as rest response with oauth2 token?

**Comment by dsyer** [comment]
Did you read the spec? OAuth2 supports a 2-legged protocol called "password" grant. But you really shouldn't use it for a browser based app.
