### ISSUE TITLE
The first request "/ token" returned: HTTP / 1.1 401 Unauthorized

### ISSUE THREAD

**Issue by mysoko** [spring-guides/tut-spring-security-and-angular-js#50]
Reference spring-session example

According to this article (https://spring.io/blog/2015/01/20/the-resource-server-angular-js-and-spring-security-part-iii) configuration, discovery token first request failed!

angular code:

``` js
angular.module('hello', [ 'ngRoute' ])
...
.controller('home', function($scope, $http) {
    $http.get('token').success(function(token) {
        $http({
            url : 'http://localhost:9000',
            method : 'GET',
            headers : {
                'X-Auth-Token' : token.token
            }
        }).success(function(data) {
            $scope.greeting = data;
        });
    })
});
```

pom.xml add spring-security:

``` xml
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
  </dependency>
```

...

The first request "/ token" returned: HTTP / 1.1 401 Unauthorized
So I do not get 'X-Auth-Token': token.token

For java code "/ token" what configuration I missed it?

**Comment by dsyer** [comment]
The first request is presumably unauthorized. Is that a surprise? What's the issue here? (Also why do you put a " " in the "/token" endpoint path?)
