### ISSUE TITLE
Spring-session resource application does not handle Chrome's OPTIONS requests

### ISSUE THREAD

**Issue by juanjose49** [spring-guides/tut-spring-security-and-angular-js#55]
@dsyer 
I'm writing because I spent several hours trying to figure out why I was receiving a "Response for preflight has invalid HTTP status code 401" from my Chrome's console. It turns out that the Resources application is sending back a 401 to the initial OPTIONS request that the Chrome browser is issuing. I resolved this issue by overriding the configure method in the WebSecurityConfigurerAdapter class with the following:

```
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
       .csrf().disable()
       .authorizeRequests()
         .antMatchers(HttpMethod.OPTIONS,"/").permitAll()//allow CORS option calls
         .antMatchers("/resources/**").permitAll()
         .anyRequest().authenticated()
       .and()
       .formLogin()
       .and()
       .httpBasic();
    }
```

Please consider adding something of this likeness to the tutorial in order to avoid confusion for future readers as it was an extremely confusing bug to resolve.

P.S.- Thank you for your Spring Session tutorial, it's been extremely helpful and mostly intuitive.

**Comment by dsyer** [comment]
I'm not sure where you are seeing that 401, but did you use the code in github? If you did then can you please be more specific and we can track it down. If you didn't, maybe you could compare your code to the sample apps and try and work out what is different. If it turns out to be an easy blunder for someone trying to follow the tutorial we can certainly change the text to reflect that. Also please note that this code is not being maintained here, and the new location is in the github homepage: https://github.com/spring-guides/tut-spring-security-and-angular-js.

**Comment by juanjose49** [comment]
I've reviewed the source code and can't really see anything that is different. To be clear though, this is a Chrome specific problem. Following along with the tutorial I was able to access the UI application, login, and see the responses from the Resource application using Safari as my browser.

When I get home later tonight, I'll try pulling your source from GitHub and try to replicate the bug.

Thanks for the prompt response,
Juan

**Comment by juanjose49** [comment]
On a slightly separate note, I want to take this opportunity to mention that you may want to consider adding a note about adding the properties for the Redis host/port to the reader's application.properties file. Being a first time Docker and Redis user it wasn't immediately obvious that the Docker/Redis instance was running on a different IP address that needed to be added to the application.properties file.

**Comment by dsyer** [comment]
Sure. Can separate notes have separate issues in github please, though?

**Comment by juanjose49** [comment]
Happy to oblige. I'll create one now. #56

**Comment by ultratt** [comment]
Did you use the CorsFilter? If you look at that class, it bypass spring security if it is "OPTIONS". So you won't get 401

**Comment by dsyer** [comment]
Yeah, it works for me too. I assume this is pilot error.
