### ISSUE TITLE
How to configure JWT authorization server without redirect

### ISSUE THREAD

**Issue by mszarlinski** [spring-guides/tut-spring-security-and-angular-js#57]
Hi, I have question regarding "oauth2" version of the example. 

Is there any easy way (or example) how to set up a JWT authorization server so that I can just log in using Angular form in UI application and access a token? This token should be automagically included in each request header and then read by a targeted micro service (I assume this part can be done without pain using @EnableResourceServer annotation and public key included in properties file). What I understand, I should use Zuul proxy to simplify routing stuff, but skip @EnableOAuth2Sso because I would use a login form of UI application and use auth server as a token provider without any user interface.

Any help would be appreciated.

**Comment by dsyer** [comment]
The whole point of the auth server is that it is a centralized resource, so putting a login form in the gateway (unless it is also the auth server) defeats the object somewhat. I don't think what you are asking makes a lot of sense consequently, and it would require custom secure code in the client which I think is a bad idea, although there seem to be many people who are prepared to attempt it. My advice is "go with the flow", and read the whole tutorial (especially the first part about the login page and using cookies where possible).
