### ISSUE TITLE
How to handle a resource calling another one with OAuth2 and JWT

### ISSUE THREAD

**Issue by grekier** [spring-guides/tut-spring-security-and-angular-js#58]
I have a working setup with multiple resource services and SSO working fine when calling them from the ui. This is based on your OAuth2 tutorial at https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/oauth2

Now I'm trying to figure out how one service can call another one and can't find any examples or tutorial. I've tried a couple of different solutions such as adding @EnableOAuth2Client to the "client" service, creating my own OAuth2ClientContextFilter and different RestTemplate setups without any luck.
The results have been variable from HTTP 401 to "A redirect is required to get the users approval"

Can you help me with any pointers?

N.B: Also worth mentioning that Eureka for service discovery is involved.

**Comment by grekier** [comment]
I found a workaround. As I checked this out more, I found that the OAuth2RestOperations didn't use Ribbon (or others) to lookup into Eureka, I autowired a LoadBalancerClient as well to do the lookup and add the correct URL in the call executed by OAuth2RestOperations. 
This is the relevant part of my controller

```
@Autowired
private OAuth2RestOperations restTemplate;
@Autowired
private LoadBalancerClient loadBalancer;

private URI getServiceUrl(String serviceName) {
    ServiceInstance serviceInstance = loadBalancer.choose(serviceName);
    return serviceInstance.getUri();
}
public void someMethod() {
...
    ResponseEntity<MyClass> responseEntity =
            restTemplate.exchange(
                    getServiceUrl("myServiceName").toString() + "/endpoint",
                    HttpMethod.GET,
                    null,
                    new ParameterizedTypeReference<MyClass>() {
                    });
...
}
```

The main class is annotated with

```
@SpringBootApplication
@EnableEurekaClient
@EnableResourceServer
```

and no other configuration is done.
It was my understanding that, when the both are present, OAuth2RestOperations should use the correct lookup mechanism without any configuration. Did I get that one wrong?

**Comment by pasha-gr** [comment]
As I know you must use a JWT encryptor and decryptor library in both side of call.

I think you can use an interceptor with high priority to decrypt encrypted data has layed in httpRequest.Headers on receiver side.
you also can use a  @ControllerAdvisor to encrypt header data you wish to send.

**Comment by dsyer** [comment]
@grekier you have to use the `@LocadBalanced` qualifier. Its in the Spring Cloud user guide I think. Not really part of this guide though.
