### ISSUE TITLE
"Get the code" block is misleading / hard to find the code

### ISSUE THREAD

**Issue by yktoo** [spring-guides/tut-spring-security-and-angular-js#6]
The block at top-right of the page saying "Get the code" leads to a repository/zip file containing 3 files with no actual content, with no slightest hint whatsoever where to find the files. It took me quite an effort to discover that the original code repository is one by "dsyer".

Yes there are *some* links to the repo in the text, but it's hard to expect one would thoroughly read a 200K+ page to find a link, so e.g. searching for "download" yielded nothing. It must be made more prominent in my humble opinion.

**Comment by dsyer** [comment]
Good point. I'm not sure why we keep the code separate from the website source (which is what the links are about). I guess the only hard thing about merging would be that the README from the original blog code at https://github.com/dsyer/spring-security-angular is more friendly for browsers than this one (which is just a source file for a web site generator). I'll have a think about how we might address that.

**Comment by dsyer** [comment]
I merged all the code and moved the old README to overview.adoc. Should be fixed now. Thanks.

**Comment by yktoo** [comment]
Great, that's quick! Thanks a bunch!
