### ISSUE TITLE
error="invalid_scope" in authorization request

### ISSUE THREAD

**Issue by muneesmajid** [spring-guides/tut-spring-security-and-angular-js#60]
When i brows home page from OAuth2 UI, and it redirect to /login and then to /uaa/oauth/authorize 
i got error empty scope. I did not  limit the scope in any configuration. there is no scope param in authorization request.

I got authorization code by including default scope in authorization request, this is executed by curl command

Handling OAuth2 error: error="invalid_scope", error_description="Empty scope (either the client or the user is not allowed the requested scopes)"

**Comment by dsyer** [comment]
You see that error if you don't explicitly request a scope in the auth request and there is none in the client configuration. The sample code in github has a scope declared here: https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/authserver/src/main/resources/application.properties#L8
