### ISSUE TITLE
Unclear behavior in the project "single" with logout

### ISSUE THREAD

**Issue by dimshust1985** [spring-guides/tut-spring-security-and-angular-js#62]
There is an unclear behavior in the module "single" or some error (https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/single). 

The function:

``` java
$scope.logout = function() {
    $http.post('logout', {}).success(function() {
        $rootScope.authenticated = false;
        $location.path("/");
    }).error(function(data) {
        console.log("Logout failed")
        $rootScope.authenticated = false;
    });
}
```

in the hello.js always return error with the status 401. But in general, logout works correct, because protected resources are not available after that. But why the success handler doesn't work ? That is the question.

**Comment by dsyer** [comment]
It's because the response from /logout is a 302 to /login (which is protected, so Angular can't load it). We could just remove the success handler.
