### ISSUE TITLE
can part v "OAUTH2" use html5Mode?

### ISSUE THREAD

**Issue by keryhu** [spring-guides/tut-spring-security-and-angular-js#63]
I use part v JWT oauth2  and angular, it works fine ! thanks !!

but, when I use  html5 Mode,  part 3, "modular"

```
@RequestMapping(value = "/{[path:[^\\.]*}")
public String redirect() {
  return "forward:/";
}
```

in my ui "index.html", `<a href="login">`  it is not redirecting to
 http://localhost:9999/uaa/login.

I have to change to  `<a href="http://localhost:9999/uaa/login">` and it redirected, when I input username and password, it redirect to "http://localhost:9988/uaa/" not expected " http://localhost:8080".

Can i use both html5 and your JWT oauth2 ?

**Comment by dsyer** [comment]
> Can i use both html5 and your JWT oauth2 ?

I don't see why not. But it's clear that if the redirect from /login isn't working, it won't help to hard code the provider URL, so you have to revert that first. You didn't show your security configuration, so I suspect the problem is there. Maybe a link to your source code would help?
