### ISSUE TITLE
formLogin

### ISSUE THREAD

**Issue by shahbour** [spring-guides/tut-spring-security-and-angular-js#65]
I tried to use formLogin instead of basic . The reason for this is i want to have the feature of redirecting to initial requested page after successful login .

After doing the changes it worked out if i login then go to any page on the UI but if i try to go to the UI directly and it prompt the login (redirect to login page on Gateway) i never get authenticated.

I think the problem is in wrong SESSION returned.

Have any one tried to use formlogin or implemented the default return url feature.

**Comment by dsyer** [comment]
I don't recommend it if you only want to collect username and password (that's why we don't use it in the samples here). The feature of returning to the original page is what is implemented in the "modular" sample I believe.
