### ISSUE TITLE
Typo in config file in documentation

### ISSUE THREAD

**Issue by matfed** [spring-guides/tut-spring-security-and-angular-js#66]
There's a typo in tutorial, here: https://spring.io/guides/tutorials/spring-security-and-angular-js/ and here: https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/README.adoc

Is:
`security.oauth2.client.scopes: openid`
should be:
`security.oauth2.client.scope: openid`

(i.e. scopes should be singular)

**Comment by dsyer** [comment]
Thanks.
