### ISSUE TITLE
Angular controller snippet error in accompanying tutorial

### ISSUE THREAD

**Issue by ddewaele** [spring-guides/tut-spring-security-and-angular-js#69]
in the [tutorial](https://spring.io/guides/tutorials/spring-security-and-angular-js/) accompanying this code, in the section `Loading a Dynamic Resource from Angular`, the greeting isn't put on the scope I suppose the user won't see the dynamic content on the page.

Shouldn't the controller looks something like this ? : 

```
angular.module('hello', [])
  .controller('home', function($scope,$http) {
  $http.get('/resource/').success(function(data) {
    $scope.greeting = data;
  })
});
```

**Comment by dsyer** [comment]
Can you be a bit more precise about where in the tutorial you think this should be (and what it would replace)? I couldn't find any snippets that looked wrong.

**Comment by dsyer** [comment]
Actually, you did say where: "in the section Loading a Dynamic Resource from Angular". But the controller there is fine (it binds the greeting to itself not to `$scope`, which is best practice as I understand it, but maybe I'm reading the wrong books).

**Comment by ddewaele** [comment]
My mistake it seems ... was following the tutorial step-by-step and didn't see the page reload until I added the `$scope`.  Must have been another issue somewhere in my project.
