### ISSUE TITLE
calling logout with POST gives 403 error

### ISSUE THREAD

**Issue by skaluva** [spring-guides/tut-spring-security-and-angular-js#71]
Hi,
I followed spring-boot-security, tutorial and followed every step.
https://spring.io/blog/2015/01/12/the-login-page-angular-js-and-spring-security-part-ii

everything is succesful except "logout". It always gives 403 error though
XSRF-TOKEN present in the request:

> {
>   "timestamp": 1455813327454,
>   "status": 403,
>   "error": "Forbidden",
>   "message": "Expected CSRF token not found. Has your session expired?",
>   "path": "/logout"
> }

And also "logoutSuccessHandler" never called. Even CsrfHeaderFilter not being called for "logout". This is my spring security config:

```
http.authorizeRequests().antMatchers("/").permitAll()
        .antMatchers("/api/**").authenticated();

        //http.csrf().disable();
        http.exceptionHandling().authenticationEntryPoint(authenticationEntryPoint);
        http.
            formLogin()
            .usernameParameter("email")
            .successHandler(authenticationSuccessHandler)
            .failureHandler(authenticationFailureHandler)
            .permitAll()
        .and()
        .logout()
            .logoutSuccessHandler(new LogoutSuccessHandler() {

                @Override
                public void onLogoutSuccess(HttpServletRequest arg0, HttpServletResponse arg1, Authentication arg2) throws IOException, ServletException {
                    logger.debug("***onLogoutSuccess***");
                }
            })
        .and()
        .addFilterAfter(new CsrfHeaderFilter(), CsrfFilter.class).csrf().csrfTokenRepository(getCsrfTokenRepository());
```

I'm totaly confused. Can anyone explain, why its not working?? and also what to do for making it work??

**Comment by todoubaba** [comment]
``` groovy
        http
            .authorizeRequests()
                .anyRequest().authenticated()
                .and()
            .csrf()
                .ignoringAntMatchers('/login', '/logout')
                .csrfTokenRepository(csrfTokenRepository())
                .and()
            .addFilterAfter(csrfHeaderFilter(), CsrfFilter.class)
```

**Comment by skaluva** [comment]
Hi,
Thanks for the reply. If we disable "csrf" protection for "/logout" as you suggested, its working fine. Now success handler also getting called. Does this mean, we need to disable "csrf" for logout POST request?  and why is it like that and why is it not mentioned in anywhere in the spring doc?

**Comment by dsyer** [comment]
It works for me (we are talking about the "single" sample in the source code?) without any explicit CSRF configuration for /logout. I suspect your client isn't sending the right header.
