### ISSUE TITLE
Does the default URL mapping contain a typo?

### ISSUE THREAD

**Issue by crazyquark** [spring-guides/tut-spring-security-and-angular-js#74]
I am referring to [this code](https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/modular/src/main/java/demo/UiApplication.java#L38)

Should it be:

```
@RequestMapping(value = "/{path:[^\\.]*}")
```

instead of:

```
@RequestMapping(value = "/{[path:[^\\.]*}")
```

?

**Comment by chaitanyathengdi** [comment]
Please edit your post to include code formatting and surround the relevant part in backticks, like so:

`@RequestMapping(value = "/{path:[^\.]}")`

I'm guessing something is getting left out, probably a `*`.

**Comment by dsyer** [comment]
Funnily enough, it doesn't matter (I assume the extra "[" is discarded by Spring MVC). Anyway I fixed it.
