### ISSUE TITLE
Use Implict grant reponse 401 from /oauth/oauthorize

### ISSUE THREAD

**Issue by tangzhe7** [spring-guides/tut-spring-security-and-angular-js#75]
the oauthoriza serve log show Invalid csrf token,the logs

> 2016-02-26 12:19:17.173 DEBUG 2544 --- [0.1-9999-exec-1] o.s.security.web.FilterChainProxy        : /oauth/authorize at position 4 of 12 in additional filter chain; firing Filter: 'CsrfFilter'
> 2016-02-26 12:19:17.191 DEBUG 2544 --- [0.1-9999-exec-1] o.s.security.web.csrf.CsrfFilter         : Invalid CSRF token found for http://localhost:9999/uaa/oauth/authorize
> 2016-02-26 12:19:17.192 DEBUG 2544 --- [0.1-9999-exec-1] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
> 2016-02-26 12:19:17.195 DEBUG 2544 --- [0.1-9999-exec-1] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed

**Comment by dsyer** [comment]
Does the auth code grant work (which is all the sample ever explicitly supported)?

**Comment by tangzhe7** [comment]
yes, Auth code grant work well
I change AuthorizationCodeResourceDetails to ImplicitResourceDetails, like this
![clientresource](https://cloud.githubusercontent.com/assets/10623716/13346857/75c4351e-dca4-11e5-8253-c81f8d7f706a.png)

and add modify application.yml,
![application yml](https://cloud.githubusercontent.com/assets/10623716/13346878/8fb826ce-dca4-11e5-8b60-28ee18f9eb4c.png)

**Comment by tangzhe7** [comment]
I have debug the Authorization Serve code, Client use POST request method to http://localhost:9999/uaa/oauth/authorize,and In Authorization Serve,POST request method does not ignored where in CsrfFilter.
So,the Authorization Serve console log that "Invalid CSRF token found for http://localhost:9999/uaa/oauth/authorize"
Sir,how should i do to make it work well?
My Authorization Serve config
![authorizationserveconfig](https://cloud.githubusercontent.com/assets/10623716/13347077/2a1324a2-dca6-11e5-90a8-f67a726fc22d.png)
My Authorization Serve WebSecurityConfig
![websecurity](https://cloud.githubusercontent.com/assets/10623716/13347833/f7aa8a64-dcaa-11e5-8c4e-bea86ed8a449.png)

**Comment by dsyer** [comment]
How come the auth code grant works then (it's the same form and the same UI)?

**Comment by tangzhe7** [comment]
yes sir,My Client and OAuthorization Serve are all use Spring OAuth2,Spring Boot.
Implict grant and Auth code grant are the same UI 
hi,dsyer
I use http Get  Method,I construct a url 
http://localhost:9999/uaa/oauth/authorize?response_type=token&client_id=233668646673605&redirect_uri=http://localhost:8080/login/oauthserve&scope=read&state=48532
It work normal.sir,thx~
