### ISSUE TITLE
Modifying the oauth2-vanilla example to seperate ui and gateway

### ISSUE THREAD

**Issue by ddewaele** [spring-guides/tut-spring-security-and-angular-js#78]
I'm trying to modify the `oauth2-vanilla` example by separating the ui and the gateway.

The idea is to access everything from the gateway (different UIs / resource backends / ....) while having a seperate Oauth2 server. So I created a new gateway app with the following routes :

```
server:
  port: 8888

zuul:
  routes:
    resource:
      url: http://localhost:9000
    user:
      url: http://localhost:9999/uaa/user
    ui:
      url: http://localhost:8080
```

And the following annotations

```
@EnableOAuth2Sso
@EnableZuulProxy
```

Now when I access the ui at http://localhost:8888/ui/ , I get a login prompt (expected) and an oauth approval (expected), but when spring redirects me back to I get one of the following errors : 

**Error 1** : Here angular-bootstrap.js was not loaded :

```
hello.js:1Uncaught ReferenceError: angular is not defined(anonymous function) @ hello.js:1
```

**Error 2** : When I hit refresh I sometimes get that both angular-bootstrap.js and hello.js fail to load

```
Refused to execute script from 'http://localhost:8888/ui/js/angular-bootstrap.js' because its MIME type ('text/css') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:8888/ui/js/hello.js' because its MIME type ('text/css') is not executable, and strict MIME type checking is enabled.
```

**Error 3** : Sometimes I see angular-bootstrap.js being loaded but not hello.js 

```
Error: [$injector:nomod] Module 'hello' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

So I seem to have an issue in getting the gateway to load up the JS files from the ui. Do I need some special configuration on the gateway (or zuul proxy) to ensure that it can load up these JS files (If I load them directly via the browser it works fine : http://localhost:8888/ui/js/angular-bootstrap.js)

If I do the following 

First type in http://localhost:8888/ui in my browser (ommiting the trailing `/`) I initially get errors because it cannot load the JS files, but when I then proceed to type http://localhost:8888/ui/ I do see the ui screen (but it shows up as unauthenticated)

All of this is done in an incognito window in Chrome.

I don't know if this is the correct place to ask these kind of questions. I'd be happy to post it on SO as well (might help others with similar issues).

**Comment by ddewaele** [comment]
Posted a question on SO as well regarding the ui / gateway splitup : http://stackoverflow.com/questions/36100395/spring-security-oauth2-sso-with-zuul-proxy

**Comment by dsyer** [comment]
The "double" sample in this tutorial has a gateway and 2 backend servers with UIs ("admin" and "ui"). I'm not sure what else we need to do to show how it works. All the problems above seem to be just config errors with paths, but it's hard to say without more analysis. Please don't cross post (I'll close this and follow up on SO if I can figure out what you did wrong).
