### ISSUE TITLE
security.sessions: if-required vs if_required

### ISSUE THREAD

**Issue by ddewaele** [spring-guides/tut-spring-security-and-angular-js#79]
The following [application.properties](https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/authserver/src/main/resources/application.properties) contains `security.sessions: if-required`

According to [the docs](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html), it should be `if_required`

**Comment by dsyer** [comment]
It doesn't matter. The values get coerced to the right format before binding.
