### ISSUE TITLE
Wro not working

### ISSUE THREAD

**Issue by malikfaiq** [spring-guides/tut-spring-security-and-angular-js#80]
Hi I am recently working on spring security with angular js and found your tutorial but for css and bootstrap wro not working.I am using Eclipse IDE and compling my code using spring boot app command in run as tab. and used maven generate resource command too.

Could you please help me out with it.

![error](https://cloud.githubusercontent.com/assets/10773864/13902041/1d4280fe-ee5a-11e5-84cf-0fa66a870187.JPG)

**Comment by zirconias** [comment]
maybe you are not referencing the right url to your resources ,  maybe  a link to your code can help figuring what is the issue.

**Comment by dsyer** [comment]
There is an Eclipse plugin for WRO. You need to install it if you are using Eclipse to build the assets (you can always use the command line still).

**Comment by nbro** [comment]
I'm using Intellij and I've having the same error.  I'm having "URI is not registered" for "http://www.isdc.ro/wro" in the file `wro.xml`:

    <groups xmlns="http://www.isdc.ro/wro">
        <group name="angular-bootstrap">
            <css>webjar:bootstrap/3.3.7/less/bootstrap.less</css>
            <css>file:./src/main/wro/main.less</css>
            <js>webjar:jquery/2.2.4/jquery.min.js</js>
            <js>webjar:angularjs/1.4.9/angular.min.js</js>
        </group>
    </groups>

I solve this "URI is not registered" by including also the dependency for wro4j as follows:

        <dependency>
            <groupId>ro.isdc.wro4j</groupId>
            <artifactId>wro4j-core</artifactId>
            <version>1.8.0</version>
        </dependency>

This doesn't give the warning anymore, but I still have the error of 404 of the resources.

**Comment by dsyer** [comment]
But you can build it from the command line? Honestly, I'm not an IntelliJ user and I don't know if there is any wro4j support. But it works if you build the assets manually.

**Comment by nbro** [comment]
Now it apparently downloaded a few dependencies, which I think it wasn't downloading before:

<img width="515" alt="screen shot 2016-11-25 at 12 50 52" src="https://cloud.githubusercontent.com/assets/9349000/20624566/e9c11cf8-b30d-11e6-9a52-3171a39472ea.png">

but when I try to access the page, I still have a few errors (I did ` mvn spring-boot:run` to start the spring boot app from the terminal):

<img width="1320" alt="screen shot 2016-11-25 at 12 50 21" src="https://cloud.githubusercontent.com/assets/9349000/20624615/32fd2416-b30e-11e6-8f3b-fef557550b67.png">


Where should these static files managed by wro4j be put?

**Comment by dsyer** [comment]
It's a bit hard to say what is happening with just a couple of screen shots. It looks like the "hello" module is not being resolved, and that is supposed to be in the classpath (from src/main/resources). I would check that IntelliJ is set up correctly and actually building the project, if that's a screenshot from the IDE.

**Comment by nbro** [comment]
Note, I've done `mvn clean install` from the terminal (I didn't use the IDE this time)! 

The screenshot is from the IDE to show you the what's been downloaded...

Anyway, under the target folder, specifically `static/`, I've inside the `js` folder a `angular-bootstrap.js` file...

**Comment by dsyer** [comment]
You're running the app on port 3000 somehow (not the way it's set up in the source code). How did you do that? If you just run it with "mvn spring-boot:run" does it work (on port 8080)?

**Comment by nbro** [comment]
In the source code, specifically in the `application.yml` file I've the following settings for the server:

```
server:
    port: 3000
```

If I do `mvn spring-boot:run` it runs on port 3000, at least that's what I'm accessing right now.

**Comment by dsyer** [comment]
Well it works for me. How about a full set of steps to reproduce (not using IntelliJ)?

**Comment by nbro** [comment]
@dsyer Sorry man, maybe I gave the wrong idea, but I'm not trying to run this project of this repository, but my own project which is based on this. I can show you the structure of my project. This is it using the `tree` tool:

        .
	├── FinancialNewsSearchEngine.iml
	├── data
	│   └── solr
	│       ├── collection1
	│       │   └── conf
	│       │       ├── schema.xml
	│       │       └── solrconfig.xml
	│       └── solr.xml
	├── mvnw
	├── mvnw.cmd
	├── phantomjsdriver.log
	├── pom.xml
	├── src
	│   ├── main
	│   │   ├── java
	│   │   │   └── financial
	│   │   │       └── news
	│   │   │           └── se
	│   │   │               ├── FinancialNewsSearchEngineApplication.java
	│   │   │               ├── controller
	│   │   │               │   ├── IndexController.java
	│   │   │               │   └── SearchController.java
	│   │   │               └── product
	│   │   │                   ├── model
	│   │   │                   │   ├── Product.java
	│   │   │                   │   └── SearchableProductDefinition.java
	│   │   │                   ├── repository
	│   │   │                   │   └── ProductRepository.java
	│   │   │                   └── service
	│   │   │                       ├── ProductService.java
	│   │   │                       └── ProductServiceImpl.java
	│   │   ├── resources
	│   │   │   ├── application.yml
	│   │   │   └── static
	│   │   │       ├── index.html
	│   │   │       └── js
	│   │   │           └── index.js
	│   │   └── wro
	│   │       ├── main.less
	│   │       ├── wro.properties
	│   │       └── wro.xml
	│   └── test
	│       └── java
	│           └── financial
	│               └── news
	│                   └── se
	│                       └── FinancialNewsSearchEngineApplicationTests.java
	└── target
	    ├── classes
	    │   ├── application.yml
	    │   ├── financial
	    │   │   └── news
	    │   │       └── se
	    │   │           ├── FinancialNewsSearchEngineApplication.class
	    │   │           ├── SearchContext.class
	    │   │           ├── controller
	    │   │           │   ├── IndexController.class
	    │   │           │   └── SearchController.class
	    │   │           └── product
	    │   │               ├── model
	    │   │               │   ├── Product.class
	    │   │               │   └── SearchableProductDefinition.class
	    │   │               ├── repository
	    │   │               │   └── ProductRepository.class
	    │   │               └── service
	    │   │                   ├── ProductService.class
	    │   │                   └── ProductServiceImpl.class
	    │   └── static
	    │       ├── css
	    │       ├── index.html
	    │       └── js
	    │           ├── angular-bootstrap.js
	    │           └── index.js
	    ├── financial-news-search-engine-0.0.1-SNAPSHOT.jar
	    ├── financial-news-search-engine-0.0.1-SNAPSHOT.jar.original
	    ├── generated-sources
	    │   └── annotations
	    ├── generated-test-sources
	    │   └── test-annotations
	    ├── jasmine
	    │   ├── SpecRunner.html
	    │   └── TEST-jasmine.xml
	    ├── maven-archiver
	    │   └── pom.properties
	    ├── maven-status
	    │   └── maven-compiler-plugin
	    │       ├── compile
	    │       │   └── default-compile
	    │       │       ├── createdFiles.lst
	    │       │       └── inputFiles.lst
	    │       └── testCompile
	    │           └── default-testCompile
	    │               ├── createdFiles.lst
	    │               └── inputFiles.lst
	    ├── phantomjs
	    │   └── phantomjs-2.1.1-macosx
	    │       └── bin
	    │           └── phantomjs
	    ├── surefire-reports
	    │   ├── TEST-financial.news.se.FinancialNewsSearchEngineApplicationTests.xml
	    │   └── financial.news.se.FinancialNewsSearchEngineApplicationTests.txt
	    └── test-classes
	        └── financial
	            └── news
	                └── se
	                    └── FinancialNewsSearchEngineApplicationTests.class

	57 directories, 49 files

**Comment by dsyer** [comment]
Sorry, I can't possibly help you with a different project with the aid only of screenshots. Does the sample code in this project work for you? Can you share the source code of your project?

**Comment by nbro** [comment]
@dsyer Ok, I've just uploaded the source code of my project: https://github.com/nbro/FinancialNewsSearchEngine

I will check if I can use yours.

**Comment by dsyer** [comment]
Your "index.html" tries to load a script called "hello.js" that doesn't exist. I imagine that's a problem (maybe not the only one)?

**Comment by nbro** [comment]
@dsyer Sorry for just answering now. Yes, I fixed that problem and renamed the files or the values of the attributes appropriately.

Nevertheless, I still have a 404 error for the resource: `http://localhost:3000/css/angular-bootstrap.css`. In fact, that resource does not seem to have been downloaded to `target/classes/static/css/`, which is empty, whereas, for example, the `angular-bootstrap.js` is in `target/classes/static/js/`.

In my opinion, this is due to the fact in the `wro.xml` I've:

```
<groups xmlns="http://www.isdc.ro/wro">

    <group name="angular-bootstrap">

        <css>webjar:bootstrap/3.3.7/less/bootstrap.less</css>
        <css>file:./src/main/wro/main.less</css>

        <js>webjar:jquery/2.2.4/jquery.min.js</js>
        <js>webjar:angularjs/1.4.9/angular.min.js</js>

    </group>

</groups>
```

Specifically I'm referring to the `bootstrap.less` under the `less` folder, but I don't have that folder anywhere...

**Comment by nbro** [comment]
@dsyer Never mind, I managed to solve the problem. The reasons I think were:

1. I had specified the wrong `bootstrap` version: I had 3.3.7, but you had specified in the `pom.xml` of the project `basic/` of this repository to be `3.3.7-1`.

2. My `wro.xml` was different (for some reason). My new `wro.xml` is:

```
<groups xmlns="http://www.isdc.ro/wro">
    <group name="angular-bootstrap">
        <css>webjar:bootstrap/3.3.7-1/less/bootstrap.less</css>
        <css>file:@project.basedir@/src/main/wro/main.less</css>
        <js>webjar:jquery/2.2.4/jquery.min.js</js>
        <js>webjar:angularjs/1.4.9/angular.min.js</js>
        <js>webjar:angularjs/1.4.9/angular-route.min.js</js>
        <js>webjar:angularjs/1.4.9/angular-cookies.min.js</js>
    </group>
</groups>
```
