### ISSUE TITLE
some dependency download links dead

### ISSUE THREAD

**Issue by chaitanyathengdi** [spring-guides/tut-spring-security-and-angular-js#82]
While building projects in this tutorial I found the IDE(Netbeans) tries to download dependencies from these links and gets stuck:
http://repository.codehaus.org/org/codehaus/groovy/groovy-eclipse-batch/maven-metadata.xml
http://nexus.codehaus.org/snapshots/org/codehaus/groovy/groovy-eclipse-batch/maven-metadata.xml

When I visited codehaus.org in chrome I got `DNS_PROBE_FINISHED_NXDOMAIN` error, meaning no such domain exists. This leads me to suspect these links won't work anymore.

Will it be possible to replace this with other links(by changing dependencies in the POM and such)?

**Comment by dsyer** [comment]
There are no "links" to those sites that we can control in this project. It's annoying, and it's a bug in the groovy-eclipse compiler pom, but not one we can fix here. If you can build on the command line though, it should work fine from an IDE (I can't say I've tried Netbeans, but it definitely still works in Eclipse).

**Comment by dsyer** [comment]
I removed all the groovy code from the samples, so this doesn't apply any more.
