### ISSUE TITLE
Does Zuul relay/proxy user identity ?

### ISSUE THREAD

**Issue by ddewaele** [spring-guides/tut-spring-security-and-angular-js#84]
@dsyer : You don't need to read the entire thing here, but I think there's an issue in the `FixedAuthoritiesExtractor` class that allows us to do role based authorizations on OAuth2Authentication objects. 

It seems `FixedAuthoritiesExtractor`  should pass on a comma-separated string of roles from the Oauth2Authentication object, but instead it passes on this string : `{authority=ROLE_ADMIN},{authority=ROLE_USER}` (= the result of an ArrayList toString).  See Update 4 for more info. If you think this is valid I'd be happy to log an issue somewhere.

Below is really a question that I'll just post to SO.

I have setup a ZuulProxy acting as a gateway to a UI and some backend resources (annotated with `@EnableResource`). What I want to achieve is something like this : 

![](https://dl.dropboxusercontent.com/u/13246619/Spring/Screenshot%202016-03-23%2015.17.48.png)
- An SSO solution where all apps / resources can be accessed through a gateway.
- A seperate authserver responsible for authenticating users / issuing access tokens
- A way to authorize users to access certain resources based on roles.
- No dependency with other components (ex: Redis for session replication)

Authenticated requests via the ZuulProxy can access the backend resources fine (The gateway will retrieve the oauth2 access token that is linked to the http session, and use that to put on the HTTP header when accessing the backend resources). All is well on that level.

However, I assumed (and now I think wrongly) that the ZuulProxy would also relay the identity (or session) to the UI. (note that the UI is not annotated with  `@EnableResource`)

When accessing the UI through the gateway, I get redirected to the authserver (expected) and when passing authentication with a user with ROLE_USER, but I get this in the gateway logs :

```
Secure object: FilterInvocation: URL: /ui/protected.html; Attributes: [authenticated]
Previously Authenticated: org.springframework.security.oauth2.provider.OAuth2Authentication@402417f1: Principal: user; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=0:0:0:0:0:0:0:1, sessionId=<SESSION>, tokenType=bearertokenValue=<TOKEN>; Granted Authorities: {authority=ROLE_USER}
Voter: org.springframework.security.web.access.expression.WebExpressionVoter@71da2205, returned: 1
Authorization successful
```

So I am seeing the OAuth2Authentication here, but this is on the gateway level where it sees /ui/protected.html. I don't think the gateway is the place to define fine-grained access control for my UI. (I want to do that in the UI itself)

However, In the UI logs (where I actually defined the authorization rules) I don't see the Oauth2Authentication anymore :

```
Secure object: FilterInvocation: URL: /protected.html; Attributes: [hasRole('ROLE_USER')]
Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@905571d8: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@0: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: CCF6C2F33B3794D28F3D45D20E59BAE0; Granted Authorities: ROLE_ANONYMOUS
Voter: org.springframework.security.web.access.expression.WebExpressionVoter@69681cd, returned: -1
AuditEvent [timestamp=Wed Mar 23 14:28:32 CET 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]
Access is denied (user is anonymous); redirecting to authentication entry point
```

**Update 1 :**

I can solve this by putting the `@EnableResource` on the UI as well. 

**Update2:** I thought I'd solved it, but by adding `@EnableResource` I'm unable to authorize on roles.

When trying to access protected resources I'm now seeing 

```
Secure object: FilterInvocation: URL: /protected.html; Attributes: [#oauth2.throwOnError(authenticated)]
```

where before I saw

```
Secure object: FilterInvocation: URL: /protected.html; Attributes: [hasRole('ROLE_USER')]
```

So it seems that despite having a Principal associated with the request/session, I cannot give access to resources based on the roles:

```
.antMatchers("/index.html", "/home.html", "/").permitAll()
.antMatchers("/protected.html").hasRole("USER")
.antMatchers("/admin.html").hasRole("ADMIN")
```

**Update 3 :**

By putting the matchers in a seperate `ResourceServerConfigurerAdapter`

```
@Configuration
@EnableResourceServer
public class ResourceConfiguration
        extends ResourceServerConfigurerAdapter
{

    @Override
    public void configure(final HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                    .antMatchers("/login").permitAll()
                    .antMatchers("/protected.html").hasRole("USER")
                    .antMatchers("/admin.html").hasRole("ADMIN");
    }
}
```

I now see a FilterInvocation with a correct OAuth2SecurityExpression, but despite having a user that should satisfy this I'm still getting an `Access is denied`.

```
Secure object: FilterInvocation: URL: /protected.html; Attributes: [#oauth2.throwOnError(hasRole('ROLE_USER'))]
Previously Authenticated: org.springframework.security.oauth2.provider.OAuth2Authentication@e6c61a39: Principal: user; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=127.0.0.1, tokenType=bearertokenValue=<TOKEN>; Granted Authorities: {authority=ROLE_USER}
Voter: org.springframework.security.web.access.expression.WebExpressionVoter@4edee618, returned: -1
AuditEvent [timestamp=Wed Mar 23 19:44:48 CET 2016, principal=user, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]
Access is denied (user is not anonymous); delegating to AccessDeniedHandler

org.springframework.security.access.AccessDeniedException: Access is denied
```

**Update 4**

After spending some quality time in my debugger, I noticed that at some point an accessDecisionManager needs to decide if I can acces the url based on the following expression :

```
#oauth2.throwOnError(hasRole('ROLE_USER'))
```

So for some reason this evaluates to false

```
        return ExpressionUtils.evaluateAsBoolean(weca.getAuthorizeExpression(), ctx) ? ACCESS_GRANTED
                : ACCESS_DENIED;
```

with my user

```
org.springframework.security.oauth2.provider.OAuth2Authentication@e6c61a39: Principal: user; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=127.0.0.1, tokenType=bearertokenValue=<TOKEN>; Granted Authorities: {authority=ROLE_USER}
```

I also noticed during debugging that the WebExpressionResolver seems to match the roles based on the string, but the Oauth2Authentication wraps it in `{authority=ROLENAME}`

![](https://dl.dropboxusercontent.com/u/13246619/Spring/Screenshot%202016-03-23%2021.12.33.png)
![](https://dl.dropboxusercontent.com/u/13246619/Spring/Screenshot%202016-03-23%2020.56.11.png)

Whereas a simple basic authentication flow uses this

![](https://dl.dropboxusercontent.com/u/13246619/Spring/Screenshot%202016-03-23%2021.06.11.png)
![](https://dl.dropboxusercontent.com/u/13246619/Spring/Screenshot%202016-03-23%2021.04.07.png)

Some questions come to mind : 
- Did I wrongfully assume that Zuul would automagically relay or proxy the identity to the underlying ui application ?
- ~~Is adding  `@EnableResource` the way to go if I want to pass on this identity to the underlying ui application ? (I don't want to resort to something like Redis to do http session replication)~~
- Should I set this up in a different way ?
- Is there a bug in the FixedAuthoritiesExtractor class to extract role based info from an OAuth2Authentication object ?

Despite activating spring security / web debug log-levels and using cURL I'm sometimes left confused at what all these annotations do and how they effect each-other. Are there any tips to further debug this ?

I have setup a [github repo ](https://github.com/ddewaele/spring-cloud-security-samples) with the code for this sample.

**Comment by dsyer** [comment]
Wow, that's a long comment (thanks for the analysis)! The short story is just that the authorities extraction is creating the wrong values for you (should be "USER" or "ROLE_USER" but it is a JSON string instead)?

**Comment by ddewaele** [comment]
It's not a JSON string. It's the result of extracting the authorities from OAuth2Authentication. The roles are stored internally as a map in a map , and the extracter assumes they are stored as a string in a map. 

So what seems to look like JSON is actually the string representation of the map element. 

![](https://dl.dropboxusercontent.com/u/13246619/Spring/Screenshot%202016-03-24%2011.35.44.png)

**Comment by ddewaele** [comment]
But I was on Brixton.M3 .. I'll check after lunch if its the same with Brixton.M5

**Comment by dsyer** [comment]
Try a snapshot (RC1 is probably today). I'll be updating the tutorial today if I get time. And ping me on gitter.im so we can sync up on how your sample works.

**Comment by dsyer** [comment]
It looks like (on investigating the sample further) the problem is more in the /user endpoint than anything else. If it was to return a custom User object with an "authorities" field that is a `Collection<String>` then the default authorities extractor would work OOTB (we can still fix it so it would have worked without this change - please open a ticket in Spring Boot for that).
