### ISSUE TITLE
How to use the token to access resources on a Resource Server

### ISSUE THREAD

**Issue by xiejx618** [spring-guides/tut-spring-security-and-angular-js#86]
I want to create a standalone resource server, I can't use the token to access my resources, it seems that the option "security.oauth2.resource.userInfoUri" does not work for me. I have uploaded my code:https://github.com/xiejx618/oauth2-vanilla.

the chrome On Windows:

```
-----------------------http://192.168.1.115:9000/ start--------------------------------
General
Request URL:http://192.168.1.115:9000/

Request Headers
Provisional headers are shown
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
-----------------------http://192.168.1.115:9000/ end-------------------------------
```

**It seems that there is no response back to chrome browse.I don't known why.**

```
-----------------------http://localhost:9000/ start--------------------------------
General
Request URL:http://localhost:9000/
Request Method:GET
Status Code:401 Unauthorized
Remote Address:127.0.0.1:9000

Response Headers
view source
Cache-Control:no-store
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Content-Type:application/xhtml+xml;charset=UTF-8
Date:Tue, 29 Mar 2016 14:51:41 GMT
Expires:0
Pragma:no-cache
Pragma:no-cache
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
WWW-Authenticate:Bearer realm="null", error="unauthorized", error_description="Full authentication is required to access this resource"
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block

Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost:9000
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

-----------------------http://localhost:9000/ end-------------------------------
```

**Why the error_description is not "An Authentication object was not found in the SecurityContext" as you said.**

```
-----------------------http://192.168.1.115:9999/uaa/user start-----------------------------
General
Request URL:http://192.168.1.115:9999/uaa/user
Request Method:GET
Status Code:401 Unauthorized
Remote Address:192.168.1.115:9999

Response Headers
view source
Cache-Control:no-store
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Content-Type:application/xhtml+xml;charset=UTF-8
Date:Tue, 29 Mar 2016 14:52:41 GMT
Expires:0
Pragma:no-cache
Pragma:no-cache
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
WWW-Authenticate:Bearer realm="null", error="unauthorized", error_description="Full authentication is required to access this resource"
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block

Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Connection:keep-alive
Host:192.168.1.115:9999
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

-----------------------http://192.168.1.115:9999/uaa/user end-------------------------------
```

**And here is normal.**

On Redhat 6.4 terminal(virtualbox machine):I have stoped iptables and selinux.

```
---------------------On Redhat 6.4 terminal(virtualbox machine) start------------------------
[root@dev ~]# curl acme:acmesecret@192.168.1.115:9999/uaa/oauth/token  \
> -d grant_type=authorization_code -d client_id=acme     \
> -d redirect_uri=http://192.168.1.115:9000 -d code=VSh3ZW
{"access_token":"e61292ab-408c-47ff-90fd-a570f982a6d5","token_type":"bearer","refresh_token":"2241c2f0-f692-434e-b184-59831e6811fa","expires_in":37504,"scope":"openid"}[root@dev ~]# TOKEN=e61292ab-408c-47ff-90fd-a570f982a6d5
[root@dev ~]# curl -H "Authorization: Bearer $TOKEN" 192.168.1.115:9999/uaa/user
{"details":{"remoteAddress":"192.168.1.194","sessionId":null,"tokenValue":"e61292ab-408c-47ff-90fd-a570f982a6d5","tokenType":"Bearer","decodedDetails":null},"authorities":[{"authority":"ROLE_USER"}],"authenticated":true,"userAuthentication":{"details":{"remoteAddress":"0:0:0:0:0:0:0:1","sessionId":null},"authorities":[{"authority":"ROLE_USER"}],"authenticated":true,"principal":{"password":null,"username":"user","authorities":[{"authority":"ROLE_USER"}],"accountNonExpired":true,"accountNonLocked":true,"credentialsNonExpired":true,"enabled":true},"credentials":null,"name":"user"},"principal":{"password":null,"username":"user","authorities":[{"authority":"ROLE_USER"}],"accountNonExpired":true,"accountNonLocked":true,"credentialsNonExpired":true,"enabled":true},"credentials":"","oauth2Request":{"clientId":"acme","scope":["openid"],"requestParameters":{"response_type":"code","grant_type":"authorization_code","redirect_uri":"http://192.168.1.115:9000","code":"VSh3ZW","client_id":"acme"},"resourceIds":[],"authorities":[{"authority":"ROLE_USER"}],"approved":true,"refresh":false,"redirectUri":"http://192.168.1.115:9000","responseTypes":["code"],"extensions":{},"grantType":"authorization_code","refreshTokenRequest":null},"clientOnly":false,"name":"user"}[root@dev ~]# 
[root@dev ~]# curl -H "Authorization: Bearer $TOKEN" 192.168.1.115:9000
curl: (7) couldn't connect to host

[root@dev ~]# curl -v 192.168.1.115:9000
* About to connect() to 192.168.1.115 port 9000 (#0)
*   Trying 192.168.1.115... 
--------------------On Redhat 6.4 terminal(virtualbox machine) end----------------------------
```

**Comment by dsyer** [comment]
That code looks like a copy of the oauth2-vanilla sample from this tutorial. Can you explain, slowly, what you changed and what it is that doesn't work as expected?

**Comment by xiejx618** [comment]
Thanks for dsyer's reply.Yes,this code is a copy of the oauth2-vanilla sample.

1.I clone this code from https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/oauth2-vanilla this morning,then I import this project to intellij idea.
2.I change nothing and start the demo.AuthserverApplication#main() method in intellij idea to run an OAuth2 Authorization Server.
3.I open a new incognito window  In Chrome,send the request http://localhost:9999/uaa/oauth/authorize?response_type=code&client_id=acme&redirect_uri=http://example.com to get authorization_code,and then I get the authorization_code 'fjRdsL'

4.My machine's LAN IP is 192.168.1.115,so I get access token on Redhat 6.4 terminal as follow:
[root@dev ~]# curl acme:acmesecret@192.168.1.115:9999/uaa/oauth/token  \
-d grant_type=authorization_code -d client_id=acme     \
-d redirect_uri=http://example.com -d code=fjRdsL
{"access_token":"8eded27d-b849-4473-8b2d-49ae49e17943","token_type":"bearer","refresh_token":"5e9af75c-c442-433f-81ba-996eb2c00f53","expires_in":43199,"scope":"openid"}
[root@dev ~]# TOKEN=8eded27d-b849-4473-8b2d-49ae49e17943
[root@dev ~]# curl -H "Authorization: Bearer $TOKEN" 192.168.1.115:9999/uaa/user
{"details":{"remoteAddress":"192.168.1.194","sessionId":null,"tokenValue":"8eded27d-b849-4473-8b2d-49ae49e17943","tokenType":"Bearer","decodedDetails":null},"authorities":[{"authority":"ROLE_USER"}],"authenticated":true,"userAuthentication":{"details":{"remoteAddress":"0:0:0:0:0:0:0:1","sessionId":"3943F6861E0FE31C29568542730342F6"},"authorities":[{"authority":"ROLE_USER"}],"authenticated":true,"principal":{"password":null,"username":"user","authorities":[{"authority":"ROLE_USER"}],"accountNonExpired":true,"accountNonLocked":true,"credentialsNonExpired":true,"enabled":true},"credentials":null,"name":"user"},"oauth2Request":{"clientId":"acme","scope":["openid"],"requestParameters":{"response_type":"code","redirect_uri":"http://example.com","code":"QzbdLe","grant_type":"authorization_code","client_id":"acme"},"resourceIds":[],"authorities":[{"authority":"ROLE_USER"}],"approved":true,"refresh":false,"redirectUri":"http://example.com","responseTypes":["code"],"extensions":{},"grantType":"authorization_code","refreshTokenRequest":null},"credentials":"","principal":{"password":null,"username":"user","authorities":[{"authority":"ROLE_USER"}],"accountNonExpired":true,"accountNonLocked":true,"credentialsNonExpired":true,"enabled":true},"clientOnly":false,"name":"user"}

Everything goes well so far.
4.Then I start the demo.ResourceApplication#main method in intellij idea to run a Resource Server,run command lines as follow:
[root@dev ~]# curl -H "Authorization: Bearer $TOKEN" 192.168.1.115:9000
curl: (7) couldn't connect to host

**It seems that it couldn't connect to 192.168.1.115,but ping 192.168.1.115,I didn't find something unusual and curl command is normal to access 192.168.1.115:9999/uaa/user, I don't know what happened?**

5.Then I come back to my local machine,open a window in chrome browser.
-----------------http://192.168.1.115:9000/ start-----------------
Request URL:http://192.168.1.115:9000/
Request Headers
Provisional headers are shown
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
-----------------http://192.168.1.115:9000/ end-------------------
**It seems that there is no response back to chrome browser.**

-----------------http://localhost:9000/ start-----------------
Request URL:http://localhost:9000/
Request Method:GET
Status Code:401 Unauthorized
Remote Address:127.0.0.1:9000

Response Headers
view source
Cache-Control:no-store
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Content-Type:application/xhtml+xml;charset=UTF-8
Date:Wed, 30 Mar 2016 02:45:27 GMT
Expires:0
Pragma:no-cache
Pragma:no-cache
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
WWW-Authenticate:Bearer realm="null", error="unauthorized", error_description="Full authentication is required to access this resource"
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block

Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost:9000
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
-----------------http://localhost:9000/ end-------------------

**Why the error_description is not "An Authentication object was not found in the SecurityContext" as you said.**

**Comment by xiejx618** [comment]
Thanks,I found what the problem is.After commented the configuration of 'server.address' in oauth2-vanilla\resource\src\main\resources\application.properties,it works.
