### ISSUE TITLE
How do I approve individual scopes in the authorize page?

### ISSUE THREAD

**Issue by ffazil** [spring-guides/tut-spring-security-and-angular-js#9]
How do I make authorize.ftl to display and approve individual scopes like the WhiteLabelApproval Endpoint? I tried to send the below key/value pairs to /oauth/authorize
read = true
write = false
But /oauth/authorize endpoint accepts both the scopes as true. Am I missing something?

**Comment by dsyer** [comment]
Something like in sparklr2 I guess: https://github.com/spring-projects/spring-security-oauth/blob/master/samples/oauth2/sparklr/src/main/webapp/WEB-INF/jsp/access_confirmation.jsp? And https://github.com/spring-projects/spring-security-oauth/blob/master/samples/oauth2/sparklr/src/main/java/org/springframework/security/oauth/examples/sparklr/mvc/AccessConfirmationController.java .

**Comment by dsyer** [comment]
It looks to me like you need to send "scope.write=false".

**Comment by ffazil** [comment]
Got it. Thanks @dsyer .
