### ISSUE TITLE
Update https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/README.adoc

### ISSUE THREAD

**Issue by qin** [spring-guides/tut-spring-security-and-angular-js#9]
The authorization grant URL actually needs a "&scope=read" param to work correctly, so does the curl call to exchange for an access token.

**Comment by qin** [comment]
In [this README file](https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/README.adoc).

**Comment by dsyer** [comment]
Works for me. Did you forget to set the scope in `application.properties`?
