### ISSUE TITLE
Call a resource with a HttpRequest which contains JWT token in java code

### ISSUE THREAD

**Issue by pasha-gr** [spring-guides/tut-spring-security-and-angular-js#97]
I am using multiple application which are hosted in one Authentication domain, one of resources acts as Authorization server and serves ACL(Access Control List) for other resources, In fact I have used an Aspect to check if current user have access to call the services as following : 
![untitled](https://cloud.githubusercontent.com/assets/17588118/15206346/b2e25ac8-1833-11e6-9ff6-55f5b4add7fc.png)

So the problem is I don't have access the authorization when I call it from Aspect ,I get 401 error .so how can I simulate the request in java code which contains security context in it?

```
@Aspect
public class AuthorizationAspect {
    @Before( "execution(public * ir.pt.discountnetwork.service.*.*(..))" //Must be in package)
    public Object checkValidity(final JoinPoint joinPoint) throws Throwable {

        String actee = makeService_key(joinPoint.getSignature().getDeclaringTypeName()
                , joinPoint.getSignature().getName(), joinPoint.getArgs());
        System.out.printf(actee);
        try {

            String uri = "http://localhost:9998/authorize/service/isGranted?service_key?" + actee;
            sendGet(uri);
            URL url = new URL(uri);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accept", "application/json");
```

And is it totally correct design? I would greatful if you tell me have better idea

**Comment by dsyer** [comment]
I don't understand the question yet. Why do you need to simulate anything? If you want to send an HTTP request with an access token attached you can use a header (manually setting it like you do with the "Accept" header above, or using an abstraction, like an `OAuth2RestTemplate`). I don't even know if that's what you want to do though, so it's a guess.

**Comment by pasha-gr** [comment]
I have an Aspect in every Resource, when a request comes from analogus UI, I just want to fetch  ACL for requested resource, but ACL Server (I name it Authorization server) is a Resource itself, so I have to call a resource ( vector 2 in the picture) from another resource. and both of them are accessible with authenticated request.
The question is when I send the request I get a 401 error because my requset doesnt have any token and authenticatin context. how can I send a authenticated request to ACL server? 
you mentioned OAuth2RestTemplate, I am confused with JWT, maybe its the cause of ambiguous question. but I know I must send arequest wich  bearers Authentication info which is encoded with JWT. how can I do that?

**Comment by dsyer** [comment]
So there's no simulation anywhere? Where does the token come from?

**Comment by pasha-gr** [comment]
Its what I exactly quest for!

**Comment by pasha-gr** [comment]
You mean I must first request an access token from authentication server? then attache it to my request?

**Comment by dsyer** [comment]
Yes. That's what the `OAuth2RestTemplate` does, if you are accepting bearer tokens on the resource servers.

**Comment by pasha-gr** [comment]
I am still struggling to get an access token! thanks for mentioning OAuth2RestTemplate .
I have this config class in Resource side So I think I did your recommendation by this way :

```
Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class CorsFilter implements Filter {
    public CorsFilter() {
    }
    @Override
    public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException {
        HttpServletResponse response = (HttpServletResponse) res;
        HttpServletRequest request = (HttpServletRequest) req;
        response.setHeader("Access-Control-Allow-Origin", "*");
        response.setHeader("Access-Control-Allow-Methods", "POST, PUT ,GET, OPTIONS, DELETE");
        response.setHeader("Access-Control-Max-Age", "3600");
        response.setHeader("Access-Control-Allow-Headers","Origin, X-Requested-With, Content-Type, Accept,x-www-form-urlencoded,access-control-allow-origin, authorization, content-type, x-requested-with");

        if ("OPTIONS".equalsIgnoreCase(request.getMethod())) {
            response.setStatus(HttpServletResponse.SC_OK);
        } else {
            chain.doFilter(req, res);
        }
    }
    @Override
    public void init(FilterConfig filterConfig) {
    }
    @Override
    public void destroy() {
    }
}

```

I use this code to send the request :

```
    public void a(String actee) {
        ResourceOwnerPasswordResourceDetails resource = new ResourceOwnerPasswordResourceDetails();
        resource.setAccessTokenUri("http://172.17.192.191:9999/uaa/oauth/token");
        resource.setAuthenticationScheme(AuthenticationScheme.header);
        resource.setClientId("my-trusted-client");
        //resource.setId("sparklr");
        resource.setScope(Arrays.asList("trust"));
        resource.setUsername("pasha");
        resource.setPassword("pasha");
        resource.setGrantType("password");
        OAuth2RestTemplate template = new OAuth2RestTemplate(resource);

        String uri = "http://172.17.192.191:9998/authorize/service/isGranted?service_key?" + actee;
        Boolean result = template.getForObject(format(uri), Boolean.class);        // System.err.println(result);
        System.out.println(result);

    }
```

and use this code in authentication server to register the client :

```
                 .withClient("my-trusted-client")
                 .authorizedGrantTypes("password", "authorization_code", "refresh_token", "implicit")
                 .scopes("trust")
                 .accessTokenValiditySeconds(60);
```

but I get error with this concept :

> error="access_denied", error_description="Access token denied."
>   at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:142)
>   at org.springframework.security.oauth2.client.token.grant.password.ResourceOwnerPasswordAccessTokenProvider.obtainAccessToken(ResourceOwnerPasswordAccessTokenProvider.java:47)
>   at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:142)
>   at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:118)
>   at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221)
>   at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
>   at org.springframework.security.oauth2.client.OAuth2RestTemplate.createRequest(OAuth2RestTemplate.java:105)
>   at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:592)
>   at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
>   at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
>   at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
>   at ir.pt.discountnetwork.config.AuthorizationAspect.a(AuthorizationAspect.java:76)
>   at ir.pt.discountnetwork.config.AuthorizationAspect.checkValidity(AuthorizationAspect.java:56)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
>   at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:603)
>   at org.springframework.aop.aspectj.AspectJMethodBeforeAdvice.before(AspectJMethodBeforeAdvice.java:40)
>   at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
>   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
>   at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
>   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
>   at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
>   at com.sun.proxy.$Proxy103.getParentList(Unknown Source)
>   at ir.pt.discountnetwork.controller.MenuController.getSubmenu(MenuController.java:60)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
>   at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
>   at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:111)
>   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:806)
>   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:729)
>   at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
>   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
>   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
>   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
>   at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
>   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
>   at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
>   at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
>   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
>   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>   at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
>   at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
>   at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
>   at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
>   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at ir.pt.discountnetwork.config.CorsFilter.doFilter(CorsFilter.java:31)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
>   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
>   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
>   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
>   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
>   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
>   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
>   at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
>   at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
>   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
>   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: error="invalid_grant", error_description="Bad credentials"
>   at org.springframework.security.oauth2.common.exceptions.OAuth2ExceptionJackson2Deserializer.deserialize(OAuth2ExceptionJackson2Deserializer.java:91)
>   at org.springframework.security.oauth2.common.exceptions.OAuth2ExceptionJackson2Deserializer.deserialize(OAuth2ExceptionJackson2Deserializer.java:33)
>   at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
>   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2206)
>   at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:221)
>   at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readInternal(AbstractJackson2HttpMessageConverter.java:200)
>   at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:161)
>   at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:235)
>   at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
>   at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
>   at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:565)
>   at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:137)
>   ... 102 more

**Comment by dsyer** [comment]
This isn't really a question about the samples in the tutorial. Better to move to StackOverflow if it's still not working.
